package com.linkly.libui;

import com.linkly.libui.currency.CountryCode;
import com.linkly.libui.display.DisplayRequest;
import com.pax.dal.entity.RSAPinKey;

import java.util.HashMap;

@SuppressWarnings("java:S115")
public interface IUIDisplay {
    int ONE_SEC_TIMEOUT = 1000;
    int ONE_MINUTE_TIMEOUT = 60 * ONE_SEC_TIMEOUT;

    int IMMEDIATE_TIMEOUT = 0;
    int SHORT_TIMEOUT = 2000;
    int THREE_SEC_TIMEOUT = 3000;
    int INFO_TIMEOUT = 4000;
    int FOUR_SEC_TIMEOUT = 4000;
    int FIVE_SEC_TIMEOUT = 5000;
    int MEDIUM_TIMEOUT = 30000; // must stay at 30 max (for getpin stuff)
    int LONG_TIMEOUT = 60000;
    int EXTRA_LONG_TIMEOUT = 80000;
    int CARD_GET_TIMEOUT = 140000;
    int GET_ACCESS_MODE_ACCOUNT_TIMEOUT = 4 * ONE_MINUTE_TIMEOUT;
    int GET_ACCESS_MODE_PIN_TIMEOUT = 4 * ONE_MINUTE_TIMEOUT; // timeout for initial and inter-button keypress
    int GET_ACCESS_MODE_PIN_TOTAL_ENTRY_TIMEOUT = 4 * ONE_MINUTE_TIMEOUT; // total pin entry timeout, very long when in access mode
    int GET_PIN_TIMEOUT = ONE_MINUTE_TIMEOUT;

    int MAX_TIMEOUT = Integer.MAX_VALUE;
    int NO_TIMEOUT = -1;

    //Display Element Tags used to pass data from Backend to Display
    String uiScreenID = "ScreenID";
    String uiScreenIcon = "ScreenIcon";
    String uiScreenIcon2 = "ScreenIcon2";
    String uiScreenTitle = "ScreenTitle";
    String uiScreenBlankType = "ScreenBlankType";
    String uiScreenPrompt = "ScreenPrompt";
    String uiScreenCurrency = "Currency";
    String uiScreenOptionList = "options";
    String uiScreenFragOptionList = "fragOptions";
    String uiScreenFragType = "fragType";
    String uiScreenMaxLen = "maxLen";
    String uiScreenMinLen = "minLen";
    String uiSkipButtonOn = "skipButtonOn";
    String uiPasswordMaxLen = "passwordMaxLen";
    String uiPasswordMinLen = "passwordMinLen";
    String uiScreenInputHint = "inputHint";
    String uiRsaPinKey = "rsaPinKey";
    String uiResultCode = "resultCode";
    String uiResultText1 = "resultText1";
    String uiResultText2 = "resultText2";
    String uiSelectChoice = "selectChoice";
    String uiPinBlock = "pinBlock";
    String uiScreenAmount = "Amount";
    String uiScreenTimeout = "ScreenTimeout";
    String uiScreenTableData = "TableData";
    String uiScreenDisableBack = "DisableBack";
    String uiLedColour = "LedColour";
    String uiLedNumber = "LedNumber";
    String uiUserUpgrade = "UserUpgrade";
    String uiUniqueId = "UniqueId";
    String uiScreenDefaultText = "DefaultText";
    String uiPresentCardTimeout = "presentCardTimeout";
    String uiKeepOnScreen = "KeepOnScreen";
    String uiQRBitmapData = "QRBitmapData";
    String uiUserDismissible = "uiUserDismissible"; // set to true to allow user to touch screen and dismiss
    String uiUserSharable = "uiUserShareable";
    String uiEnableBackButton = "uiEnableBackButton";
    String uiButtonPrompt = "uiButtonPrompt";
    String uiDisableScreensaver = "uiDisableScreensaver";
    String uiTitleId = "uiTitleId";
    String uiPromptId = "uiPromptId";
    String uiPromptIdArg = "uiPromptIdArg";
    String uiButtonPromptId = "uiButtonPromptId";
    String uiInputHintId = "uiInputHintId";
    String uiTitleArg = "uiTitleArg";
    String uiError = "uiError";

    //////////////////////////////////////////////////////////////////// NEW FUNCTIONS //////////////////////////////////////////////////////////////////////////
    void showScreen(UIScreenDef def, String... promptArg);

    void showScreen(UIScreenDef def, String_id titleId, String... promptArg);

    void showScreen(UIScreenDef def, HashMap<String, Object> mExtras, String... promptArg);

    void showInputScreen(UIScreenDef def, HashMap<String, Object> mExtras, String... promptArgs);

    void displayMainMenuScreen();

    void displayPleaseWaitScreen();

    void cancelScreenSaver();

    void resetScreenSaver();

    void getPin(SCREEN_ID iType, RSAPinKey rsaPinKey, String transactionName, String prompt, long amount, CountryCode cCode);

    UIResultCode getResultCode(IUIDisplay.ACTIVITY_ID activityId, int iTimeoutMS);
    void displayLed2(boolean one, boolean two, boolean three, boolean four);

    /********************************************************************************************************/
    // Proper Interface functions
    boolean getSelectChoice(ACTIVITY_ID iActivityID, String textName);

    String getResultText(IUIDisplay.ACTIVITY_ID activityId, String textName); // call getResultCode to get the response first, then call this to get additional text

    boolean getResultBoolean(IUIDisplay.ACTIVITY_ID activityId, String boolName);

    byte[] getResultPinBlock(IUIDisplay.ACTIVITY_ID activityId);

    void sendResponse(DisplayRequest uiMessage, HashMap<String, Object> map);

    void sendResponse(DisplayRequest uiMessage, IUIDisplay.UIResultCode uiResultCode, HashMap<String, Object> map);

    void sendResponse(DisplayRequest uiMessage, IUIDisplay.UIResultCode uiResultCode, String sResult1, String sResult2);

    enum ACTIVITY_ID {
        ACT_MAIN_MENU,
        ACT_INFORMATION,
        ACT_INPUT,
        ACT_INPUT_PIN,
        ACT_INPUT_AMOUNT,
        ACT_INPUT_AMOUNT_IDLE,
        ACT_ACCESS_APP_SELECTION,
        ACT_USER_LOGIN,
        ACT_GET_CARD,
        ACT_QUESTION,
        ACT_ADD_TIP,
        ACT_PICK_GRATUITY,
        ACT_TABLE,
        ACT_INSTALL,
        ACT_BIG_INFO,
        ACT_SCREEN_PRINT,
        ACT_REBOOT,
        ACT_QR_SCAN,
        ACT_QR_CODE,
        ACT_BLANK, // just used to wrap other activities (hack)
        ACT_SCREEN_SAVER, // used for enabling/disabling screensaver in app
        ACT_IDLE,
        ACT_INFORMATION_BASIC,
        ACT_LOYALTY_POST_CARD_PRESENTED,
        ACT_LOYALTY_POST_TRANSACTION,
        ACT_LOYALTY_POST_AMOUNT_ENTRY,
        ACT_DEFERRED_AUTHS,
        ACT_TRANS_FINISH,
        ACT_SIG,
        ACT_SELECT_ACCOUNT,
        ACT_ANIMATED_PRINT,
        ACT_SELECT_APPLICATION,
        ACT_SAF_VIEW_AND_CLEAR,
        ACT_PRE_AUTH_SEARCH_AND_VIEW_SELECT_DATE,
        ACT_PRE_AUTH_SEARCH_AND_VIEW,
        ACT_TRANSACTION_HISTORY
    }

    enum SCREEN_ID {
        NOT_SET,
        MAIN_MENU,
        ADMIN_MENU,
        //STATUS_SCREEN,
        GET_USER,
        OFFLINE_PIN,
        ONLINE_PIN,

        // options for ACT_GET_CARD
        GET_CARD_MAN,
        GET_CARD_ICC,
        GET_CARD_CTLS,
        GET_CARD_MSR,
        GET_CARD_ICC_MAN,
        GET_CARD_ICC_CTLS,
        GET_CARD_ICC_MSR,
        GET_CARD_CTLS_MAN,
        GET_CARD_CTLS_MSR,
        GET_CARD_MSR_MAN,
        GET_CARD_MSR_ICC_MAN,
        GET_CARD_MSR_ICC_CTLS,
        GET_CARD_MSR_MAN_CTLS,
        GET_CARD_MAN_CTLS_ICC,
        GET_CARD_MSR_ICC_CTLS_MAN,
        GET_CARD_CDCVM,

        //Input Screen
        GET_INPUT_ALPHA,
        GET_INPUT_ALPHA_NUMERIC,
        GET_INPUT_ALPHA_NUMERIC_CAPS,
        GET_INPUT_ALPHA_NUMERIC_CAPS_NO_SYM,
        GET_INPUT_NUMERIC_ALPHA,
        GET_INPUT_NUMERIC_ALPHA_NO_SYM,
        GET_INPUT_NUMBER,
        GET_INPUT_NUMBER_PASSWORD,
        GET_INPUT_PASSWORD,
        GET_INPUT_PHONE_NO,
        GET_INPUT_EMAIL
    }

    enum SCREEN_ICON {
        NO_ICON,
        INFO_ICON,
        WARNING_ICON,
        ERROR_ICON,
        ERROR_ICON_WITH_BEEP,
        SUCCESS_ICON,
        PROCESSING_ICON,
        PROCESSING_ICON_STILL,
        PRINTING_ICON,
        BUTTON_ICON,
        IN_PROGRESS
    }

    enum UIResultCode {
        UNKNOWN,
        OK,
        FAIL,
        ABORT,
        MANUAL,
        EXCEPTION,
        CARDREAD,
        TIMEOUT,
        BYPASSED,
        READY, // used to indicate that the pin callbacks are ready to go, not that the activity has finished
        /**
         * Special result code.
         * Used to restart the get card fragment
         * */
        RESTART,
        /**
         * Special Result code, to be used when POS sends YES key for YES/NO screens
         * */
        POS_YES
    }

    // allows us to configure additional fragments to display on screens (like the AskQuestionActivity at this point
    enum FRAG_TYPE {
        FRAG_NOT_SET,
        FRAG_MOTO,
        FRAG_GRID,
        FRAG_GRID_GENERIC
    }

    enum String_id {
        STR_APP_NAME(R.string.app_name),
        STR_SIGNAL_STRENGTH(R.string.SIGNAL_STRENGTH),
        STR_PING_RESULT(R.string.PING_RESULT),
        STR_SUCCESS(R.string.SUCCESS),
        STR_FAILED(R.string.FAILED),
        STR_MPOS(R.string.MPOS),
        STR_ALREADY_CONNECTED(R.string.ALREADY_CONNECTED),
        STR_CONNECTING(R.string.CONNECTING),
        STR_CONNECT_SUCCESS(R.string.CONNECT_SUCCESS),
        STR_CONNECT_FAILED_PLEASE_CHECK_DEVICE(R.string.CONNECT_FAILED_PLEASE_CHECK_DEVICE),
        STR_DISCONNECTING(R.string.DISCONNECTING),
        STR_DISCONNECT_COMPLETED(R.string.DISCONNECT_COMPLETED),
        STR_ALREADY_DISCONNECT(R.string.ALREADY_DISCONNECT),
        STR_SEARCHING(R.string.SEARCHING),
        STR_DEVICES_FOUND(R.string.DEVICES_FOUND),
        STR_SELECT_YOUR_DEVICE(R.string.SELECT_YOUR_DEVICE),
        STR_SAVED_DEVICE(R.string.SAVED_DEVICE),
        STR_CONFIG_LOADED(R.string.CONFIG_LOADED),
        STR_CONFIG_LOADING(R.string.CONFIG_LOADING),
        STR_CONFIG_LOAD_ERROR(R.string.CONFIG_LOAD_ERROR),
        STR_NOT_CONNECTED_PLEASE_CONNECT_FIRST(R.string.NOT_CONNECTED_PLEASE_CONNECT_FIRST),
        STR_LOADING_FIRMWARE(R.string.LOADING_FIRMWARE),
        STR_FIRMWARE_UP_TO_DATE(R.string.FIRMWARE_UP_TO_DATE),
        STR_FIRMWARE_UPDATE_ERROR(R.string.FIRMWARE_UPDATE_ERROR),
        STR_MPOS_WIZARD(R.string.MPOS_WIZARD),
        STR_SEARCHING_FOR(R.string.SEARCHING_FOR),
        STR_SEARCHING_CR(R.string.SEARCHING_CR),
        STR_PROCESSING(R.string.PROCESSING),
        STR_CHECKING_LOYALTY(R.string.CHECKING_LOYALTY),
        STR_PROCESSING_LOYALTY_CTLS(R.string.PROCESSING_LOYALTY_CTLS),
        STR_PLEASE_WAIT(R.string.PLEASE_WAIT),
        STR_CASHIER_ADDED(R.string.CASHIER_ADDED),
        STR_UPDATING_CONFIG(R.string.UPDATING_CONFIG),
        STR_APPLYING_CONFIG(R.string.APPLYING_CONFIG),
        STR_PASSWORD_INCORRECT(R.string.PASSWORD_INCORRECT),
        STR_PASSWORD_INCORRECT_TRY_AGAIN(R.string.PASSWORD_INCORRECT_TRY_AGAIN),
        STR_INSUFFICIENT_PRIVILEGES(R.string.INSUFFICIENT_PRIVILEGES),
        STR_CASHIER_NOT_FOUND(R.string.CASHIER_NOT_FOUND),
        STR_FAILED_TO_LOGIN(R.string.FAILED_TO_LOGIN),
        STR_BATCH_UPLOAD(R.string.BATCH_UPLOAD),
        STR_PENDING(R.string.PENDING),
        STR_NO_TRANS_TO_UPLOAD(R.string.NO_TRANS_TO_UPLOAD),
        STR_CASHIER_LOCKED(R.string.CASHIER_LOCKED),
        STR_SERVICE_STATUS(R.string.SERVICE_STATUS),
        STR_PING_TEST(R.string.PING_TEST),
        STR_TEST_PUBLIC_SERVICES(R.string.TEST_PUBLIC_SERVICES),
        STR_LOG_CLEAR(R.string.LOG_CLEAR),
        STR_PLEASE_WAIT_BR(R.string.PLEASE_WAIT_BR),
        STR_LOG_EMPTY(R.string.LOG_EMPTY),
        STR_SUCCESSFUL(R.string.SUCCESSFUL),
        STR_TESTING_PAYMENT_SERVICE(R.string.TESTING_PAYMENT_SERVICE),
        STR_SOFTWARE_UPDATED(R.string.SOFTWARE_UPDATED),
        STR_CHECKING_PLEASE_WAIT(R.string.CHECKING_PLEASE_WAIT),
        STR_DATABASE_CLEAR(R.string.DATABASE_CLEAR),
        STR_DATABASE_CLEARED(R.string.DATABASE_CLEARED),
        STR_PING_TEST_SUCCESSFUL(R.string.PING_TEST_SUCCESSFUL),
        STR_PING_TEST_FAILED(R.string.PING_TEST_FAILED),
        STR_UPDATE_FAILED(R.string.UPDATE_FAILED),
        STR_FAILED_TO_ADD(R.string.FAILED_TO_ADD),
        STR_TEST_KEY_INJECT(R.string.TEST_KEY_INJECT),
        STR_UDP_DEBUGGING(R.string.UDP_DEBUGGING),
        STR_DATABASE_LIST(R.string.DATABASE_LIST),
        STR_DATABASE_EMPTY(R.string.DATABASE_EMPTY),
        STR_ID_ALREADY_USED(R.string.ID_ALREADY_USED),
        STR_NO_ENTRIES(R.string.NO_ENTRIES),
        STR_PASSWORD_UPDATED(R.string.PASSWORD_UPDATED),
        STR_FAILED_TO_DELETE(R.string.FAILED_TO_DELETE),
        STR_FAILED_LC(R.string.FAILED_LC),
        STR_CARD_ALREADY_LINKED(R.string.CARD_ALREADY_LINKED),
        STR_CASHIER_DELETE(R.string.CASHIER_DELETE),
        STR_OPERATION_NOT_ALLOWED(R.string.OPERATION_NOT_ALLOWED),
        STR_ICC_DIAGS(R.string.ICC_DIAGS),
        STR_DISABLED(R.string.DISABLED),
        STR_PASSWORD_EXPIRED(R.string.PASSWORD_EXPIRED),
        STR_PASSWORD_RESET(R.string.PASSWORD_RESET),
        STR_USER_PASSWORD(R.string.USER_PASSWORD),
        STR_USER_INITIAL_PASSCODE(R.string.USER_INITIAL_PASSCODSE),
        STR_FAILURE(R.string.FAILURE),
        STR_RESET_FAILED(R.string.RESET_FAILED),
        STR_USER_REPORT(R.string.USER_REPORT),
        STR_CASHIERS_NOT_FOUND(R.string.CASHIERS_NOT_FOUND),
        STR_FAILED_TO_LOCK_CASHIER(R.string.FAILED_TO_LOCK_CASHIER),
        STR_CASHIER_UNLOCKED(R.string.CASHIER_UNLOCKED),
        STR_CASHIER_DELETED(R.string.CASHIER_DELETED),
        STR_PASSWORD_DOESNT_MATCH(R.string.PASSWORD_DOESNT_MATCH),
        STR_ENABLED(R.string.ENABLED),
        STR_UDP_PING_TEST(R.string.UDP_PING_TEST),
        STR_TESTING_PUBLIC_SERVICES(R.string.TESTING_PUBLIC_SERVICES),
        STR_CTLS_NOT_ENABLED(R.string.CTLS_NOT_ENABLED),
        STR_TRANSACTION_ERROR(R.string.TRANSACTION_ERROR),
        STR_CARD_REMOVED_EARLY(R.string.CARD_REMOVED_EARLY),
        STR_TOTAL_REPORT(R.string.TOTAL_REPORT),
        STR_TOTALS_REPORT(R.string.TOTALS_REPORT),
        STR_CLEAR_TOTALS(R.string.CLEAR_TOTALS),
        STR_NO_DATA_AVAILABLE(R.string.NO_DATA_AVAILABLE),
        STR_READING_CARD(R.string.READING_CARD),
        STR_BUDGET(R.string.BUDGET),
        STR_VALUE_EXCEEDS_MAX(R.string.VALUE_EXCEEDS_MAX),
        STR_CARD_TYPE_NOT_ALLOWED(R.string.CARD_TYPE_NOT_ALLOWED),
        STR_NO_PAIRED_MPOS(R.string.NO_PAIRED_MPOS),
        STR_PLEASE_CONFIGURE_DEVICE(R.string.PLEASE_CONFIGURE_DEVICE),
        STR_BATTERY_LOW_PLEASE_CHARGE(R.string.BATTERY_LOW_PLEASE_CHARGE),
        STR_PAPER_OUT_PLEASE_INSERT(R.string.PAPER_OUT_PLEASE_INSERT),
        STR_ERROR(R.string.ERROR),
        STR_PRINTER_ERROR(R.string.PRINTER_ERROR),
        STR_CLOSE_BRACKET(R.string.CLOSE_BRACKET),
        STR_NO_TRANSACTION_TO_RECONCILE(R.string.NO_TRANSACTION_TO_RECONCILE),
        STR_RECONCILIATION(R.string.RECONCILIATION),
        STR_LAST_RECONCILIATION(R.string.LAST_RECONCILIATION),
        STR_PRE_RECONCILIATION(R.string.PRE_RECONCILIATION),
        STR_MAC_FAILURE(R.string.MAC_FAILURE),
        STR_NOT_AVAILABLE_PLEASE_CONNECT(R.string.NOT_AVAILABLE_PLEASE_CONNECT),
        STR_INVALID_RECEIPT_NUMBER(R.string.INVALID_RECEIPT_NUMBER),
        STR_INVALID_AMOUNT(R.string.INVALID_AMOUNT),
        STR_UNABLE_TO_REVERSE(R.string.UNABLE_TO_REVERSE),
        STR_UNABLE_TO_REVERSE_TOO_OLD(R.string.UNABLE_TO_REVERSE_TOO_OLD),
        STR_ALREADY_REVERSED(R.string.ALREADY_REVERSED),
        STR_REVERSAL(R.string.REVERSAL),
        STR_TIME_DATE_ERROR(R.string.TIME_DATE_ERROR),
        STR_TIMESYNC(R.string.TIMESYNC),
        STR_TRANSACTION_TYPE_CANT_BE_REVERSED(R.string.TRANSACTION_TYPE_CANT_BE_REVERSED),
        STR_COMMS_ERROR(R.string.COMMS_ERROR),
        STR_INQUIRY_FAILED(R.string.INQUIRY_FAILED),
        STR_CASH_IN_FAILED(R.string.CASH_IN_FAILED),
        STR_DAILY_LIMIT_EXCEDED(R.string.DAILY_LIMIT_EXCEDED),
        STR_NO_CUSTOMER_RECORD(R.string.NO_CUSTOMER_RECORD),
        STR_NOT_PERMITTED(R.string.NOT_PERMITTED),
        STR_REASON(R.string.REASON),
        STR_CONNECTION_FAILED(R.string.CONNECTION_FAILED),
        STR_NO_TRANSACTION_FOUND(R.string.NO_TRANSACTION_FOUND),
        STR_DUPLICATE_SESSION(R.string.DUPLICATE_SESSION_ID),
        STR_DUPLICATE_TXNREF(R.string.DUPLICATE_TXN_REF),
        STR_INITIALISING(R.string.INITIALISING),
        STR_BLUETOOTH_NOT_ENABLED(R.string.BLUETOOTH_NOT_ENABLED),
        STR_CONNECT_FAILED(R.string.CONNECT_FAILED),
        STR_SETTING_UP_TRANS(R.string.SETTING_UP_TRANS),
        STR_SEE_CARD_READER(R.string.SEE_CARD_READER),
        STR_TRANSACTION_PROCESSING(R.string.TRANSACTION_PROCESSING),
        STR_TRANSACTION_FAILED(R.string.TRANSACTION_FAILED),
        STR_TRANSACTION_DECLINED(R.string.TRANSACTION_DECLINED),
        STR_CANT_FIND_THE_LATEST(R.string.CANT_FIND_THE_LATEST),
        STR_CANT_REVERSE_A_REFUND(R.string.CANT_REVERSE_A_REFUND),
        STR_CANT_REVERSE_OFFLINE_AN_ONLINE_APPROVED_TRANS(R.string.CANT_REVERSE_OFFLINE_AN_ONLINE_APPROVED_TRANS),
        STR_SEE_CARD_READER_ONLINE_PIN(R.string.SEE_CARD_READER_ONLINE_PIN),
        STR_AUTH_CODE(R.string.AUTH_CODE),
        STR_PLEASE_NOTE(R.string.PLEASE_NOTE),
        STR_REPRINT(R.string.REPRINT),
        STR_RECEIPT_NOT_FOUND(R.string.RECEIPT_NOT_FOUND),
        STR_BATTERY_TOO_LOW(R.string.BATTERY_TOO_LOW),
        STR_PAPER_OUT(R.string.PAPER_OUT),
        STR_OPEN_BRACKET(R.string.OPEN_BRACKET),
        STR_PRINTING_CR(R.string.PRINTING_CR),
        STR_PRINTING(R.string.PRINTING),
        STR_COMPLETED(R.string.COMPLETED),
        STR_PRINTER(R.string.PRINTER),
        STR_OUT_OF_PAPER(R.string.OUT_OF_PAPER),
        STR_ENTER_USER_ID(R.string.ENTER_USER_ID),
        STR_ENTER_PASSWORD(R.string.ENTER_PASSWORD),
        STR_ENTER_NAME(R.string.ENTER_NAME),
        STR_NEW_CASHIER(R.string.NEW_CASHIER),
        STR_GRANT_SUPERVISOR_PERMISSIONS(R.string.GRANT_SUPERVISOR_PERMISSIONS),
        STR_SWIPE_TO_LOGIN(R.string.SWIPE_TO_LOGIN),
        STR_DO_YOU_WISH_TO_ADD_CARD(R.string.DO_YOU_WISH_TO_ADD_CARD),
        STR_DELETE_CASHIER(R.string.DELETE_CASHIER),
        STR_ARE_YOU_SURE_YOU_WANT_TO_DELETE(R.string.ARE_YOU_SURE_YOU_WANT_TO_DELETE),
        STR_AUTH_REQUIRED(R.string.AUTH_REQUIRED),
        STR_ENTER_SUPERVISOR_PASSWORD(R.string.ENTER_SUPERVISOR_PASSWORD),
        STR_WELCOME(R.string.WELCOME),
        STR_ENTER_USER_CREDENTIALS(R.string.ENTER_USER_CREDENTIALS),
        STR_ENTER_EXISTING_PASSWORD(R.string.ENTER_EXISTING_PASSWORD),
        STR_ENTER_NEW_PASSWORD(R.string.ENTER_NEW_PASSWORD),
        STR_NEW_PASSWORD(R.string.NEW_PASSWORD),
        STR_REENTER_NEW_PASSWORD(R.string.REENTER_NEW_PASSWORD),
        STR_WHICH_COPY_IS_REQUIRED(R.string.WHICH_COPY_IS_REQUIRED),
        STR_ENTER_RECEIPT_NUM(R.string.ENTER_RECEIPT_NUM),
        STR_DAILY_BATCH_REPORT(R.string.DAILY_BATCH_REPORT),
        STR_REVERSAL_UPLOAD(R.string.REVERSAL_UPLOAD),
        STR_SELECT_OPTION(R.string.SELECT_OPTION),
        STR_RETRY(R.string.RETRY),
        STR_DISMISS(R.string.DISMISS),
        STR_SELECT_TYPE(R.string.SELECT_TYPE),
        STR_SOFTWARE_UPDATE_AVAILABLE(R.string.SOFTWARE_UPDATE_AVAILABLE),
        STR_RUN_UPDATE_NOW(R.string.RUN_UPDATE_NOW),
        STR_PLEASE_ENTER_MONTHS(R.string.PLEASE_ENTER_MONTHS),
        STR_BUDGET_PAYMENTS(R.string.BUDGET_PAYMENTS),
        STR_IDENTITY_CONFIRMED(R.string.IDENTITY_CONFIRMED),
        STR_SIG_CORRECT(R.string.SIG_CORRECT),
        STR_AUTHORISED(R.string.AUTHORISED),
        STR_DECLINED(R.string.DECLINED),
        STR_CANCELLED(R.string.CANCELLED),
        STR_NL_CANCELLED(R.string.NL_CANCELLED),
        STR_EXCEPTION(R.string.EXCEPTION),
        STR_PRINT_WARNING(R.string.PRINT_WARNING),
        STR_REMOVE_CARD(R.string.REMOVE_CARD),
        STR_READ_ERROR_REMOVE_CARD(R.string.READ_ERROR_REMOVE_CARD),
        STR_FLIGHT_MODE(R.string.FLIGHT_MODE),
        STR_ENABLE_AIRPLANE_MODE(R.string.ENABLE_AIRPLANE_MODE),
        STR_OFFLINE_TOTALS(R.string.OFFLINE_TOTALS),
        STR_EMAIL_TRIGGER_DO_YOU_NEED_RECEIPT(R.string.EMAIL_TRIGGER_DO_YOU_NEED_RECEIPT),
        STR_CUSTOMER_EMAIL(R.string.CUSTOMER_EMAIL),
        STR_PLEASE_ENTER(R.string.PLEASE_ENTER),
        STR_EMAIL_TRIGGER_IS_CORRECT(R.string.EMAIL_TRIGGER_IS_CORRECT),
        STR_FLIGHT_MODE_MAX_EXCEEDED(R.string.FLIGHT_MODE_MAX_EXCEEDED),
        STR_CALL_CARD_CENTRE(R.string.CALL_CARD_CENTRE),
        STR_AUTHORISED_BY_CARD_CENTRE(R.string.AUTHORISED_BY_CARD_CENTRE),
        STR_MOTO_CONFIRMED(R.string.MOTO_CONFIRMED),
        STR_REMOVE_CARDHOLDER_COPY(R.string.REMOVE_CARDHOLDER_COPY),
        STR_MERCHANT_COPY(R.string.MERCHANT_COPY),
        STR_REMOVE_MERCHANT_COPY(R.string.REMOVE_MERCHANT_COPY),
        STR_SKIP(R.string.SKIP),
        STR_ENTER_POST_CODE(R.string.ENTER_POST_CODE),
        STR_PROMPT(R.string.PROMPT),
        STR_SCAN_QR(R.string.SCAN_QR),
        STR_VALIDATING_CODE(R.string.VALIDATING_CODE),
        STR_CONFIRM(R.string.CONFIRM),
        STR_CANCEL(R.string.CANCEL),
        STR_PRINT_USER_LOG(R.string.PRINT_USER_LOG),
        STR_DELETE_USER_LOG(R.string.DELETE_USER_LOG),
        STR_USER_LOG(R.string.USER_LOG),
        STR_SELECT_ACTION(R.string.SELECT_ACTION),
        STR_DELETED(R.string.DELETED),
        STR_DELETING_PLS_WAIT(R.string.DELETING_PLS_WAIT),
        STR_FULL(R.string.FULL),
        STR_SHORT(R.string.SHORT),
        STR_DATABASE_STATS(R.string.DATABASE_STATS),
        STR_DATABASE_COUNTS(R.string.DATABASE_COUNTS),
        STR_TOTAL_RECORDS(R.string.TOTAL_RECORDS),
        STR_TOTAL_SALES(R.string.TOTAL_SALES),
        STR_TOTAL_SALES_REVERSALS(R.string.TOTAL_SALES_REVERSALS),
        STR_TOTAL_REFUNDS(R.string.TOTAL_REFUNDS),
        STR_TOTAL_REFUND_REVERSALS(R.string.TOTAL_REFUND_REVERSALS),
        STR_NO(R.string.NO),
        STR_YES(R.string.YES),
        STR_OUT_OF_SEQUENCE(R.string.OUT_OF_SEQUENCE),
        STR_TRY_INSERT_SWIPE_OTHER(R.string.TRY_INSERT_SWIPE_OTHER),
        STR_WALLET_TRANS_NOT_ALLOWED_TRY_ANOTHER(R.string.WALLET_TRANS_NOT_ALLOWED_TRY_ANOTHER),
        STR_TRY_CONTACT_TRANS(R.string.TRY_CONTACT_TRANS),
        STR_TRY_CONTACT_MSR_TRANS(R.string.TRY_CONTACT_MSR_TRANS),
        STR_ZERO_TRANS_AMOUNT(R.string.ZERO_TRANS_AMOUNT),
        STR_CARD_READ_ERROR(R.string.CARD_READ_ERROR),
        STR_CARD_REPORT_ERROR(R.string.CARD_REPORT_ERROR),
        STR_ERROR_PRESENT_ONE_CARD(R.string.ERROR_PRESENT_ONE_CARD),
        STR_OVER_MAX_LIMIT(R.string.OVER_MAX_LIMIT),
        STR_REQ_ONLINE_AUTH(R.string.REQ_ONLINE_AUTH),
        STR_CARD_BLOCKED(R.string.CARD_BLOCKED),
        STR_CARD_EXPIRED(R.string.CARD_EXPIRED),
        STR_CARD_TYPE_NOT_SUPPORT(R.string.CARD_TYPE_NOT_SUPPORT),
        STR_CARD_NO_RESPOND(R.string.CARD_NO_RESPOND),
        STR_CARD_NOT_PRESENT(R.string.CARD_NOT_PRESENT),
        STR_UNKNOWN_ELEMENT(R.string.UNKNOWN_ELEMENT),
        STR_CARD_TYPE_NOT_READ(R.string.CARD_TYPE_NOT_READ),
        STR_CARD_TERMINATED(R.string.CARD_TERMINATED),
        STR_CARD_DECLINED(R.string.CARD_DECLINED),
        STR_CARD_NOT_ACCEPTED(R.string.CARD_NOT_ACCEPTED),
        STR_ONLINE_REQUIRED(R.string.ONLINE_REQUIRED),
        STR_SDA_DDN_NO_SUPPORT(R.string.SDA_DDN_NO_SUPPORT),
        STR_MISSING_CAPK(R.string.MISSING_CAPK),
        STR_ISSUER_ERROR(R.string.ISSUER_ERROR),
        STR_CARD_AUTH_FAIL(R.string.CARD_AUTH_FAIL),
        STR_CARD_KEY_ERROR(R.string.CARD_KEY_ERROR),
        STR_CARD_SIG_ERROR(R.string.CARD_SIG_ERROR),
        STR_PROC_REST_FAIL(R.string.PROC_REST_FAIL),
        STR_TRM_FAILED(R.string.TRM_FAILED),
        STR_CVM_FAIL(R.string.CVM_FAIL),
        STR_TAA_FAIL(R.string.TAA_FAIL),
        STR_SD_MEM_ERROR(R.string.SD_MEM_ERROR),
        STR_TRANS_TIMEOUT(R.string.TRANS_TIMEOUT),
        STR_TRANS_CANCEL(R.string.TRANS_CANCEL),
        STR_RECEIPT_NUMBER(R.string.RECEIPT_NUMBER),
        STR_PLEASE_CHOOSE(R.string.PLEASE_CHOOSE),
        STR_REVERSE_LAST(R.string.REVERSE_LAST),
        STR_REFUND_LAST(R.string.REFUND_LAST),
        STR_VOID(R.string.VOID),
        STR_AMOUNT_CAPS(R.string.AMOUNT_CAPS),
        STR_ENTER_PIN(R.string.ENTER_PIN),
        STR_ENTER_HERE(R.string.ENTER_HERE),
        STR_ENTER_AUTH_CODE(R.string.ENTER_AUTH_CODE),
        STR_ENTER_PREAUTH_AUTHCODE(R.string.ENTER_PREAUTH_AUTHCODE),
        STR_ENTER_EFB_AUTH_NUMBER(R.string.ENTER_EFB_AUTH_NUMBER),
        STR_ENTER_PREAUTH_RRN_CODE(R.string.ENTER_PREAUTH_RRN_CODE),
        STR_REFERENCE(R.string.REFERENCE),
        STR_ENTER_REFERENCE(R.string.ENTER_REFERENCE),
        STR_ACCOUNT_TYPE(R.string.ACCOUNT_TYPE),
        STR_MAIL_ORDER(R.string.MAIL_ORDER),
        STR_TELEPHONE(R.string.TELEPHONE),
        STR_FAULTY_CARD(R.string.FAULTY_CARD),
        STR_SAVINGS(R.string.SAVINGS),
        STR_CHEQUE(R.string.CHEQUE),
        STR_CHEQUE_DEBIT(R.string.CHEQUE_DEBIT),
        STR_CREDIT(R.string.CREDIT),
        STR_DEFAULT(R.string.DEFAULT),
        STR_ENTER_TIP_SALE(R.string.ENTER_TIP_SALE),
        STR_ENTER_TOTAL_SALE(R.string.ENTER_TOTAL_SALE),
        STR_TOTAL_TOO_LOW(R.string.TOTAL_TOO_LOW),
        STR_TRY_AGAIN(R.string.TRY_AGAIN),
        STR_TOTAL_AMOUNT(R.string.TOTAL_AMOUNT),
        STR_TOTAL_AMOUNT_ENTERED(R.string.TOTAL_AMOUNT_ENTERED),
        STR_TIP_AMOUNT_ENTERED(R.string.TIP_AMOUNT_ENTERED),
        STR_EXCEEDS_LIMIT(R.string.EXCEEDS_LIMIT),
        STR_TOTAL_AMOUNT_TOO_LARGE(R.string.TOTAL_AMOUNT_TOO_LARGE),
        STR_SALE(R.string.SALE),
        STR_GRATUITY(R.string.GRATUITY),
        STR_SURCHARGE(R.string.SURCHARGE),
        STR_SCG(R.string.SCG),
        STR_CASHBACK(R.string.CASHBACK),
        STR_CASHBACK_ONLY(R.string.CASHBACK_ONLY),
        STR_CASHBACK_SHORT(R.string.CASHBACK_SHORT),
        STR_TOTAL(R.string.TOTAL),
        STR_CORRECT(R.string.CORRECT),
        STR_SUMMARY(R.string.SUMMARY),
        STR_BACK(R.string.BACK),
        STR_ACCEPT(R.string.ACCEPT),
        STR_OTHER(R.string.OTHER),
        STR_NONE(R.string.NONE),
        STR_BALANCE(R.string.BALANCE),
        STR_DO_ADD_GRATUITY(R.string.DO_ADD_GRATUITY),
        STR_IS_HOLDER_PRESENT(R.string.IS_HOLDER_PRESENT),
        STR_RUNNING(R.string.RUNNING),
        STR_ENTER_TOTAL_PREAUTH_AMT(R.string.ENTER_TOTAL_PREAUTH_AMT),
        STR_ENTER_AMOUNT(R.string.ENTER_AMOUNT),
        STR_CASHBACK_TOO_LARGE(R.string.CASHBACK_TOO_LARGE),
        STR_CASHBACK_REQUIRED(R.string.CASHBACK_REQUIRED),
        STR_ENTER_TIP(R.string.ENTER_TIP),
        STR_ENTER_TOTAL(R.string.ENTER_TOTAL),
        STR_ENTER_HOUSE_NUMBER(R.string.ENTER_HOUSE_NUMBER),
        STR_IS_SIGN_REQUIRED(R.string.IS_SIGN_REQUIRED),
        STR_CONGRATS_RECEIVE_DISCOUNT(R.string.CONGRATS_RECEIVE_DISCOUNT),
        STR_OFF_YOUR_TOTAL(R.string.OFF_YOUR_TOTAL),
        STR_CANCELLING_VOUCHER(R.string.CANCELLING_VOUCHER),
        STR_COPY(R.string.COPY),
        STR_REMOVE(R.string.REMOVE),
        STR_OK(R.string.OK),
        STR_CONTINUE(R.string.CONTINUE),
        STR_ENTER_PHONE_NO(R.string.ENTER_PHONE_NO),
        STR_PHONE_NO(R.string.PHONE_NO),
        STR_CUSTOMER(R.string.CUSTOMER),
        STR_WAS_TRANS_IN(R.string.WAS_TRANS_IN),
        STR_EXCHANGE_RATE(R.string.EXCHANGE_RATE),
        STR_INCLUDES(R.string.INCLUDES),
        STR_MARGIN(R.string.MARGIN),
        STR_ADMIN_PASSWORD(R.string.ADMIN_PASSWORD),
        STR_ENTER_ADMIN_PASSWORD(R.string.ENTER_ADMIN_PASSWORD),
        STR_SECURITY_CHECK(R.string.SECURITY_CHECK),
        STR_MONTHS(R.string.MONTHS),
        STR_PERMISSIONS_ERROR(R.string.PERMISSIONS_ERROR),
        STR_SUPERVISOR_LOGIN(R.string.SUPERVISOR_LOGIN),
        STR_TRANS_NOT_ALLOWED(R.string.TRANS_NOT_ALLOWED),
        STR_INVALID_CARD_NUMBER(R.string.INVALID_CARD_NUMBER),
        STR_RE_ENTER(R.string.RE_ENTER),
        STR_AMOUNT_TOO_SMALL(R.string.AMOUNT_TOO_SMALL),
        STR_AMOUNT_TOO_LARGE(R.string.AMOUNT_TOO_LARGE),
        STR_MINIMUM(R.string.MINIMUM),
        STR_MAXIMUM(R.string.MAXIMUM),
        STR_ATM_ONLY(R.string.ATM_ONLY),
        STR_INSERT_CARD(R.string.INSERT_CARD),
        STR_CASH_NOT_ALLOW(R.string.CASH_NOT_ALLOW),
        STR_CASH_ONLY_CARD(R.string.CASH_ONLY_CARD),
        STR_OFFLINE_TRANS_NOT_ALLOW(R.string.OFFLINE_TRANS_NOT_ALLOW),
        STR_TERMINAL_NOT_CONFIGURED(R.string.TERMINAL_NOT_CONFIGURED),
        STR_DATABASE_FULL(R.string.DATABASE_FULL),
        STR_HOUSE(R.string.HOUSE),
        STR_POSTCODE(R.string.POSTCODE),
        STR_GET_CARD(R.string.GET_CARD),
        STR_PRESENT_ONE_CARD(R.string.PRESENT_ONE_CARD),
        STR_CHIP_WARNING(R.string.CHIP_WARNING),
        STR_CONTLESS_WARNING(R.string.CONTLESS_WARNING),
        STR_USER_ID(R.string.USER_ID),
        STR_PASSWORD(R.string.PASSWORD),
        STR_DISPLAY_NAME(R.string.DISPLAY_NAME),
        STR_DEPARTMENT(R.string.DEPARTMENT),
        STR_PASSWORD_CHANGE_NOT_ALLOW(R.string.PASSWORD_CHANGE_NOT_ALLOW),
        STR_AMOUNT(R.string.AMOUNT),
        STR_SAVE_CREDS(R.string.SAVE_CREDS),
        STR_USER_LOGIN(R.string.USER_LOGIN),
        STR_SENDING(R.string.SENDING),
        STR_UPLOADED(R.string.UPLOADED),
        STR_UPLOAD_WILL_CONTINUE(R.string.UPLOAD_WILL_CONTINUE),
        STR_DELAY_5_MINUTES(R.string.DELAY_5_MINUTES),
        STR_CARD_NOT_READ_PROP(R.string.CARD_NOT_READ_PROP),
        STR_KEYS_RESET(R.string.KEYS_RESET),
        STR_ENTER_CARD_EASE_REFERENCE(R.string.ENTER_CARD_EASE_REFERENCE),
        STR_Z_BALANCE(R.string.Z_BALANCE),
        STR_X_BALANCE(R.string.X_BALANCE),
        STR_CARD_READ_OK(R.string.CARD_READ_OK),
        STR_PLEASE_TRY_AGAIN(R.string.PLEASE_TRY_AGAIN),
        STR_TRANS_APPROVED(R.string.TRANS_APPROVED),
        STR_TRANS_APPROVED_PROMPT(R.string.TRANS_APPROVED_PROMPT),
        STR_TRANS_APPROVED_SIGN(R.string.TRANS_APPROVED_SIGN),
        STR_TRANS_DECLINED(R.string.TRANS_DECLINED),
        STR_TRANS_DECLINED_PROMPT(R.string.TRANS_DECLINED_PROMPT),
        STR_TRY_ANOTHER_CARD(R.string.TRY_ANOTHER_CARD),
        STR_PLEASE_INSERT_CARD(R.string.PLEASE_INSERT_CARD),
        STR_SEE_CONSUMER_DEVICE(R.string.SEE_CONSUMER_DEVICE),
        STR_AUTHORISING_PLEASE_WAIT(R.string.AUTHORISING_PLEASE_WAIT),
        STR_CARD_OK_REMOVE(R.string.CARD_OK_REMOVE),
        STR_PLEASE_NL_REMOVE_CARD(R.string.PLEASE_NL_REMOVE_CARD),
        STR_REFUND(R.string.REFUND),
        STR_MONDAY(R.string.MONDAY),
        STR_TUESDAY(R.string.TUESDAY),
        STR_WEDNESDAY(R.string.WEDNESDAY),
        STR_THURSDAY(R.string.THURSDAY),
        STR_FRIDAY(R.string.FRIDAY),
        STR_SATURDAY(R.string.SATURDAY),
        STR_SUNDAY(R.string.SUNDAY),
        STR_JANUARY(R.string.JANUARY),
        STR_FEBRUARY(R.string.FEBRUARY),
        STR_MARCH(R.string.MARCH),
        STR_APRIL(R.string.APRIL),
        STR_MAY(R.string.MAY),
        STR_JUNE(R.string.JUNE),
        STR_JULY(R.string.JULY),
        STR_AUGUST(R.string.AUGUST),
        STR_SEPTEMBER(R.string.SEPTEMBER),
        STR_OCTOBER(R.string.OCTOBER),
        STR_NOVEMBER(R.string.NOVEMBER),
        STR_DECEMBER(R.string.DECEMBER),
        STR_NO_SIGNAL(R.string.NO_SIGNAL),
        STR_LOW_SIGNAL(R.string.LOW_SIGNAL),
        STR_AVERAGE_SIGNAL(R.string.AVERAGE_SIGNAL),
        STR_GOOD_SIGNAL(R.string.GOOD_SIGNAL),
        STR_EXCELLENT_SIGNAL(R.string.EXCELLENT_SIGNAL),
        STR_PAYMENT_APP(R.string.PAYMENT_APP),
        STR_SERVICE_APP(R.string.SERVICE_APP),
        STR_UPDATE_NOW(R.string.UPDATE_NOW),
        STR_UPDATE_LATER(R.string.UPDATE_LATER),
        STR_MAG_STRIPE(R.string.MAG_STRIPE),
        STR_CANCEL_RETURN_MENU(R.string.CANCEL_RETURN_MENU),
        STR_PLEASE(R.string.PLEASE),
        STR_FOR_INSTRUCTIONS(R.string.FOR_INSTRUCTIONS),
        STR_PLEASE_TAP_SWIPE_OR_INSERT(R.string.PLEASE_TAP_SWIPE_OR_INSERT),
        STR_PLEASE_SWIPE_OR_INSERT(R.string.PLEASE_SWIPE_OR_INSERT),
        STR_PLEASE_TAP_OR_INSERT(R.string.PLEASE_TAP_OR_INSERT),
        STR_PLEASE_TAP_OR_SWIPE(R.string.PLEASE_TAP_OR_SWIPE),
        STR_PLEASE_TAP(R.string.PLEASE_TAP),
        STR_PLEASE_SWIPE(R.string.PLEASE_SWIPE),
        STR_PLEASE_INSERT(R.string.PLEASE_INSERT),
        STR_MANUAL_ENTRY(R.string.MANUAL_ENTRY),
        STR_SYSTEM_REBOOTING(R.string.SYSTEM_REBOOTING),
        STR_NETWORK_NAME(R.string.NETWORK_NAME),
        STR_CONNECTION_TYPE(R.string.CONNECTION_TYPE),
        STR_NOT_CONNECTED(R.string.NOT_CONNECTED),
        STR_NO_INTERNET_BASE_NOT_REQUIRED(R.string.NO_INTERNET_BASE_NOT_REQUIRED),
        STR_NO_INTERNET_BASE_REQUIRED(R.string.NO_INTERNET_BASE_REQUIRED),
        STR_STORED_TRANSACTIONS(R.string.STORED_TRANSACTIONS),
        STR_DEPARTMENT_ID(R.string.DEPARTMENT_ID),
        STR_TERMINAL_ID(R.string.TERMINAL_ID),
        STR_MERCHANT_ID(R.string.MERCHANT_ID),
        STR_LAST_REPORT(R.string.LAST_REPORT),
        STR_LAST_UPDATE(R.string.LAST_UPDATE),
        STR_MAIN_MENU(R.string.MAIN_MENU),
        STR_ADMIN_MENU(R.string.ADMIN_MENU),
        STR_SEE_CONSUMER_DEVICE_FOR_INST(R.string.SEE_CONSUMER_DEVICE_FOR_INST),
        STR_CONNECTING_TO_HOST(R.string.CONNECTING_TO_HOST),
        STR_SENDING_MSG_BR(R.string.SENDING_MSG_BR),
        STR_WAITING_FOR_RESPONSE_BR(R.string.WAITING_FOR_RESPONSE_BR),
        STR_COMMS_FAILURE(R.string.COMMS_FAILURE),
        STR_RECEIVING_RESPONSE_BR(R.string.RECEIVING_RESPONSE_BR),
        STR_TRANSACTION_CANCELLED(R.string.TRANSACTION_CANCELLED),
        STR_REFUND_NOT_PRESENT(R.string.REFUND_NOT_PRESENT),
        STR_CASH(R.string.CASH),
        STR_PRE_AUTH(R.string.PRE_AUTH),
        STR_PRE_AUTH_MOTO(R.string.PRE_AUTH_MOTO),
        STR_PRE_AUTH_CANCEL(R.string.PRE_AUTH_CANCEL),
        STR_COMPLETION(R.string.COMPLETION),
        STR_PRE_AUTH_COMPLETION(R.string.PRE_AUTH_COMPLETION),
        STR_TOPUP_PRE_AUTH(R.string.TOPUP_PRE_AUTH),
        STR_TOPUP_COMPLETION(R.string.TOPUP_COMPLETION),
        STR_DEPOSIT(R.string.DEPOSIT),
        STR_OFFLINE_SALE(R.string.OFFLINE_SALE),
        STR_OFFLINE_CASH(R.string.OFFLINE_CASH),
        STR_TEST_CONNECT(R.string.TEST_CONNECT),
        STR_TEST_CYCLE_KEYS(R.string.TEST_CYCLE_KEYS),
        STR_PROC_TRANS_PLEASE_WAIT_BR(R.string.PROC_TRANS_PLEASE_WAIT_BR),
        STR_PROC_TRANS_PLEASE_WAIT_BR_1(R.string.PROC_TRANS_PLEASE_WAIT_BR_1),
        STR_PROC_TRANS_PLEASE_WAIT_BR_2(R.string.PROC_TRANS_PLEASE_WAIT_BR_2),
        STR_DATA_FAILURE_RESPONSE_INVALID_BR(R.string.DATA_FAILURE_RESPONSE_INVALID_BR),
        STR_COMMS_FAILURE_RESPONSE_INVALID_BR(R.string.COMMS_FAILURE_RESPONSE_INVALID_BR),
        STR_NOT_IMPLEMENTED(R.string.NOT_IMPLEMENTED),
        STR_COMPLETION_AMOUNT_CHECK(R.string.COMPLETION_AMOUNT_CHECK),
        STR_CONNECTING_TO_HOST_1(R.string.CONNECTING_TO_HOST_1),
        STR_CONNECTING_TO_HOST_2(R.string.CONNECTING_TO_HOST_2),
        STR_COMMS_FAILURE_VAR_RESPONSE_BR(R.string.COMMS_FAILURE_VAR_RESPONSE_BR),
        STR_MINIMUM_VAR_BR(R.string.MINIMUM_VAR_AMT_BR),
        STR_MAXIMUM_VAR_BR(R.string.MAXIMUM_VAR_AMT_BR),
        STR_CALL_CARD_CENTRE_NL_VAR(R.string.CALL_CARD_CENTRE_NL_VAR),
        STR_VAR_AMT_NL_VAR_NL_EXCEEDS_LIMITS_VAR(R.string.VAR_AMT_NL_VAR_NL_EXCEEDS_LIMIT_VAR),
        STR_PRINTER_ERROR_VAR_BR(R.string.PRINTER_ERROR_VAR_BR),
        STR_PENDING_EVENTS(R.string.PENDING_EVENTS),
        STR_NO_PENDING_EVENTS(R.string.NO_PENDING_EVENTS),
        STR_CANDIDATE_LIST_EMPTY(R.string.CANDIDATE_LIST_EMPTY),
        STR_PIN_BLOCKED(R.string.PIN_BLOCKED),
        STR_APP_BLOCKED(R.string.APP_BLOCKED),
        STR_CAPK_NOT_FOUND(R.string.CAPK_NOT_FOUND),
        STR_APPLICATION_NL_EXPIRED(R.string.APPLICATION_NL_EXPIRED),
        STR_APPLICATION_NOT_NL_YET_EFFECTIVE(R.string.APPLICATION_NOT_NL_YET_EFFECTIVE),
        STR_LAST_PIN_TRY(R.string.LAST_PIN_TRY),
        STR_INVALID_PIN_NL_ENTERED(R.string.INVALID_PIN_NL_ENTERED),
        STR_CHIP_READ_ERROR_NL_CANDIDATE_LIST_EMPTY_BR(R.string.CHIP_READ_ERROR_NL_CANDIDATE_LIST_EMPTY_BR),
        STR_CHIP_READ_OK(R.string.CHIP_READ_OK),
        STR_CARD_COMMAND_NL_FAILED(R.string.CARD_COMMAND_NL_FAILED),
        STR_VAR_VAR_BR_NL_PLEASE_WAIT(R.string.VAR_VAR_BR_NL_PLEASE_WAIT),
        STR_VAR_NL_PLEASE_WAIT(R.string.VAR_NL_PLEASE_WAIT),
        STR_NL_COMPLETED(R.string.NL_COMPLETED),
        STR_NL_NL_REMOVE_CARD(R.string.NL_NL_REMOVE_CARD),
        STR_NL_READING_CARD(R.string.NL_READING_CARD),
        STR_VAR_PENDING(R.string.VAR_PENDING),
        STR_USER_DELETE(R.string.USER_DELETE),
        STR_USER_DELETED(R.string.USER_DELETED),
        STR_USERS_NOT_FOUND(R.string.USERS_NOT_FOUND),
        STR_USER_NOT_FOUND(R.string.USER_NOT_FOUND),
        STR_USER_ADDED(R.string.USER_ADDED),
        STR_ADD_USER_CANCELLED(R.string.ADD_USER_CANCELLED),
        STR_NEW_USER(R.string.NEW_USER),
        STR_DELETE_USER(R.string.DELETE_USER),
        STR_APP_SELECTION(R.string.APP_SELECTION),
        STR_SENDING_VAR_OF_VAR(R.string.SENDING_VAR_OF_VAR),
        STR_UPLOADED_VAR_OF_VAR_NL_UPLOAD_WILL_CONTINUE(R.string.UPLOADED_VAR_OF_VAR_NL_UPLOAD_WILL_CONTINUE),
        STR_NL_REMOVE_NL_VAR_COPY(R.string.NL_REMOVE_NL_VAR_COPY),
        STR_INPUT_HINT_4LEN(R.string.INPUT_HINT_4LEN),
        STR_INPUT_HINT_3LEN(R.string.INPUT_HINT_3LEN),
        STR_NUMBER(R.string.NUMBER),
        STR_IS_CASH_BACK_NL_REQUIRED_NL_NL(R.string.IS_CASH_BACK_NL_REQUIRED_NL_NL),
        STR_SALE_VAR_NL_GRATUITY_VAR_NL_TOTAL_VAR_NL_CORRECT(R.string.SALE_VAR_NL_GRATUITY_VAR_NL_TOTAL_VAR_NL_CORRECT),
        STR_SALE_VAR_NL_GRATUITY_VAR_NL_CASH_BACK_VAR_NL_TOTAL_VAR_NL_CORRECT(R.string.SALE_VAR_NL_GRATUITY_VAR_NL_CASH_BACK_VAR_NL_TOTAL_VAR_NL_CORRECT),
        STR_RECONCILIATION_MENU_BTN(R.string.RECONCILIATION_MENU_BTN),
        STR_PRE_RECONCILIATION_MENU_BTN(R.string.PRE_RECONCILIATION_MENU_BTN),
        STR_LAST_RECONCILIATION_MENU_BTN(R.string.LAST_RECONCILIATION_MENU_BTN),
        STR_TEST_ACQUIRING_CONNECTION(R.string.TEST_ACQUIRING_CONNECTION),
        STR_SYSTEM_INFO(R.string.SYSTEM_INFO),
        STR_SUBMIT_TRANS(R.string.SUBMIT_TRANS),
        STR_HISTORY_REPORT(R.string.HISTORY_REPORT),
        STR_X_REPORT(R.string.X_REPORT),
        STR_DCC_RATES(R.string.DCC_RATES),
        STR_LICENSE(R.string.LICENSE),
        STR_REPRINT_MAN(R.string.REPRINT_MAN),
        STR_REPRINT_LAST(R.string.REPRINT_LAST),
        STR_REPRINT_NUM(R.string.REPRINT_NUM),
        STR_REPRINT_REC(R.string.REPRINT_REC),
        STR_DOWNLOAD_MAN(R.string.DOWNLOAD_MAN),
        STR_UPDATE(R.string.UPDATE),
        STR_FORCE_UPDATE(R.string.FORCE_UPDATE),
        STR_USER_MAN(R.string.USER_MAN),
        STR_SYS_INFO_MENU(R.string.SYS_INFO_MENU),
        STR_LOGIN_TEST(R.string.LOGIN_TEST),
        STR_ADD_USER(R.string.ADD_USER),
        STR_CHANGE_PASSWORD(R.string.CHANGE_PASSWORD),
        STR_RESET_PASSWORD(R.string.RESET_PASSWORD),
        STR_DATABASE_MAN(R.string.DATABASE_MAN),
        STR_CHECK_SERVICE(R.string.CHECK_SERVICE),
        STR_CLEAR_KEYS(R.string.CLEAR_KEYS),
        STR_TEST_SCHEDULE(R.string.TEST_SCHEDULE),
        STR_TEST_ADD_TRANS(R.string.TEST_ADD_TRANS),
        STR_TEST_AUTO_DOWNLOAD(R.string.TEST_AUTO_DOWNLOAD),
        STR_TEST_ADD_TIME(R.string.TEST_ADD_TIME),
        STR_ICC_DIAG(R.string.ICC_DIAG),
        STR_PURGE_FILE_SYSTEM(R.string.PURGE_FILE_SYSTEM),
        STR_INJECT_KEY(R.string.INJECT_KEY),
        STR_RESET_KEYS(R.string.RESET_KEYS),
        STR_SALE_AUTO(R.string.SALE_AUTO),
        STR_REVERSAL_AUTO(R.string.REVERSAL_AUTO),
        STR_PREAUTH_AUTO(R.string.PREAUTH_AUTO),
        STR_COMPLETION_AUTO(R.string.COMPLETION_AUTO),
        STR_REFUND_AUTO(R.string.REFUND_AUTO),
        STR_FIVE_PERCENT(R.string.FIVE_PERCENT),
        STR_TEN_PERCENT(R.string.TEN_PERCENT),
        STR_FIFTEEN_PERCENT(R.string.FIFTEEN_PERCENT),
        STR_TWENTY_PERCENT(R.string.TWENTY_PERCENT),
        STR_BOTH(R.string.BOTH),
        STR_MERCHANT_ONLY(R.string.MERCHANT_ONLY),
        STR_CUSTOMER_ONLY(R.string.CUSTOMER_ONLY),
        STR_TRANSACTION_BR_VAR(R.string.TRANSACTION_BR_VAR),
        STR_UID_VAR(R.string.UID_VAR),
        STR_STATE_VAR(R.string.STATE_VAR),
        STR_MSG_STATUS_VAR(R.string.MSG_STATUS_VAR),
        STR_APPROVED_VAR(R.string.APPROVED_VAR),
        STR_AMOUNT_VAR(R.string.AMOUNT_VAR),
        STR_CASH_BACK_AMOUNT_VAR(R.string.CASH_BACK_AMOUNT_VAR),
        STR_GRATUITY_VAR(R.string.GRATUITY_VAR),
        STR_HOST_RESULT_VAR(R.string.HOST_RESULT_VAR),
        STR_AUTH_METHOD_VAR(R.string.AUTH_METHOD_VAR),
        STR_STAN_VAR(R.string.STAN_VAR),
        STR_STAN(R.string.STAN),
        STR_STAN_INV(R.string.STAN_INV),
        STR_BATCH_NO(R.string.BATCH_NO),
        STR_AUTH_CODE_VAR(R.string.AUTH_CODE_VAR),
        STR_RRN_VAR(R.string.RRN_VAR),
        STR_BATCH_VAR(R.string.BATCH_VAR),
        STR_UTI_VAR(R.string.UTI_VAR),
        STR_SHOW_MESSAGES_FOR_UID_VAR(R.string.SHOW_MESSAGES_FOR_UID_VAR),
        STR_REC_VAR(R.string.REC_VAR),
        STR_REVERSALS_VAR(R.string.REVERSALS_VAR),
        STR_NL_PLEASE_WAIT(R.string.NL_PLEASE_WAIT),
        STR_VAR(R.string.VAR),
        STR_DECLINED_VAR(R.string.DECLINED_VAR),
        STR_AUTHORISED_VAR(R.string.AUTHORISED_VAR),
        STR_NL_AUTHORISED(R.string.NL_AUTHORISED),
        STR_NL_AUTHORISED_WITH_SIG( R.string.NL_AUTHORISED_WITH_SIG ),
        STR_VAR_NL_PROCESSING(R.string.VAR_NL_PROCESSING),
        STR_VAR_NL_PROCESSING_ELLIPSIS(R.string.VAR_NL_PROCESSING_ELLIPSIS),
        STR_ENTER_TOTAL_SALE_VAR(R.string.ENTER_TOTAL_SALE_VAR),
        STR_ENTER_TIP_SALE_VAR(R.string.ENTER_TIP_SALE_VAR),
        STR_TRANSACTION_DETAILS(R.string.TRANSACTION_DETAILS),
        STR_TRANSACTION_LIST(R.string.TRANSACTION_LIST),
        STR_DEFER_AUTH(R.string.DEFER_AUTH),
        STR_DEFERRED_AUTHS(R.string.DEFERRED_AUTHS),
        STR_SHOW_DEFERRED_AUTHS(R.string.SHOW_DEFERRED_AUTHS),
        STR_DEFERRED_AUTH(R.string.DEFERRED_AUTH),
        STR_DEFERRED_AUTH_WARNING(R.string.DEFERRED_AUTH_WARNING),
        STR_DEFERED_AUTH_DECLINED(R.string.DEFERRED_AUTH_DECLINED),
        STR_ACCESS_MODE(R.string.ACCESS_MODE),
        STR_ACCESS_MODE_ENABLED(R.string.ACCESS_MODE_ENABLED),
        STR_ACCESS_MODE_DISABLED(R.string.ACCESS_MODE_DISABLED),
        STR_MAL_NO_SIGNAL(R.string.MAL_NO_SIGNAL),
        STR_MAL_LOW_SIGNAL(R.string.MAL_LOW_SIGNAL),
        STR_MAL_AVERAGE_SIGNAL(R.string.MAL_AVERAGE_SIGNAL),
        STR_MAL_GOOD_SIGNAL(R.string.MAL_GOOD_SIGNAL),
        STR_MAL_EXCELLENT_SIGNAL(R.string.MAL_EXCELLENT_SIGNAL),
        STR_CELLULAR_SETTINGS(R.string.CELLULAR_SETTINGS),
        STR_AIRPLANE_MODE(R.string.AIRPLANE_MODE),
        STR_TEST_MULTIPATH(R.string.TEST_MULTIPATH),
        STR_LOGOUT(R.string.LOGOUT),
        STR_SETTINGS(R.string.SETTINGS),
        STR_WIFI_SETTINGS(R.string.WIFI_SETTINGS),
        STR_SOUND_SETTINGS(R.string.SOUND_SETTINGS),
        STR_APN_SETTINGS(R.string.APN_SETTINGS),
        STR_DISPLAY_SETTINGS(R.string.DISPLAY_SETTINGS),
        STR_APP_SETTINGS(R.string.APP_SETTINGS),
        STR_EXIT(R.string.EXIT),
        STR_REBOOT_PROMPT(R.string.REBOOT_PROMPT),
        STR_REBOOT_CONFIRMATION(R.string.REBOOT_CONFIRM),
        STR_REBOOT_CANCEL(R.string.REBOOT_CANCEL),
        STR_ERROR_INVALID_USERID(R.string.ERROR_INVALID_USERID),
        STR_ERROR_FIELD_REQUIRED(R.string.ERROR_FIELD_REQUIRED),
        STR_ERROR_PASSWORD_TOO_SHORT(R.string.ERROR_PASSWORD_TOO_SHORT),
        STR_ERROR_PASSCODE_BTW_6_12(R.string.ERROR_PASSCODE_BTW_6_12),
        STR_BATTERY_LOW(R.string.BATTERY_LOW),
        STR_PRINT_OUT(R.string.PRINT_OUT),
        STR_PIN(R.string.PIN),
        STR_SHARE_RECEIPT(R.string.SHARE_RECEIPT),
        STR_DONE(R.string.DONE),
        STR_PLEASE_SELECT_ENV(R.string.PLEASE_SELECT_ENV),
        STR_PREPROD(R.string.PREPROD),
        STR_QA(R.string.QA),
        STR_TEST(R.string.TEST),
        STR_LIVE(R.string.LIVE),
        STR_MERCHANT_STORE_ID(R.string.MERCHANT_STORE_ID),
        STR_STORE_ID(R.string.STORE_ID),
        STR_LICENSE_KEY(R.string.LICENSE_KEY),
        STR_STORE_KEY(R.string.STORE_KEY),
        STR_ACTIVATE_FAILED(R.string.ACTIVATE_FAILED),
        STR_PLEASE_RETRY(R.string.PLEASE_RETRY),
        STR_LAST_AUTO_REC(R.string.LAST_AUTO_REC),
        STR_LAST_REBOOT_TIME(R.string.LAST_REBOOT_TIME),
        STR_DOWNLOAD_STATUS(R.string.DOWNLOAD_STATUS),
        STR_DOWNLOAD_REASON(R.string.DOWNLOAD_REASON),
        STR_LAST_DOWNLOAD_DATE(R.string.LAST_DOWNLOAD_DATE),
        STR_LAST_AUTO_DOWNLOAD(R.string.LAST_AUTO_DOWNLOAD),
        STR_ACTIVATE(R.string.ACTIVATE),
        STR_DEACTIVATE(R.string.DEACTIVATE),
        STR_EXIT_KIOSK(R.string.EXIT_KIOSK),
        STR_RUN_UPDATE(R.string.RUN_UPDATE),
        STR_DOWNLOAD_MANAGER(R.string.DOWNLOAD_MANAGER),
        STR_CHECK_UPDATES(R.string.CHECK_UPDATES),
        STR_CONFIG_NOT_AVAILABLE_TRY_AGAIN(R.string.CONFIG_NOT_AVAILABLE_TRY_AGAIN),
        STR_FORCE_CHECK_UPDATES(R.string.CHECK_UPDATES),
        STR_DOWNLOAD_IN_PROGRESS(R.string.DOWNLOAD_IN_PROGRESS),
        STR_SECTION(R.string.SECTION),
        STR_VERSION(R.string.VERSION),
        STR_UNAVAILABLE(R.string.UNAVAILABLE),
        STR_ACTIVATING(R.string.ACTIVATING),
        STR_AP_SETUP(R.string.AP_SETUP),
        STR_SSID(R.string.SSID),
        STR_AP_PASSWORD(R.string.AP_PASSWORD),
        STR_DHCP_START_IP(R.string.DHCP_START_IP),
        STR_DHCP_END_IP(R.string.DHCP_END_IP),
        STR_APPLY(R.string.APPLY),
        STR_APPLIED(R.string.APPLIED),
        STR_APPLYING(R.string.APPLYING),
        STR_TESTING_CONNECTION(R.string.TESTING_CONNECTION),
        STR_NEXT(R.string.NEXT),
        STR_CANCEL_SETUP(R.string.CANCEL_SETUP),
        STR_ENABLE_WIFI_BASE_DHCP(R.string.ENABLE_WIFI_BASE_DHCP),
        STR_LAN_SETUP(R.string.LAN_SETUP),
        STR_CONFIGURE_STATIC_IP(R.string.CONFIGURE_STATIC_IP),
        STR_CONFIGURE_DHCP(R.string.CONFIGURE_DHCP),
        STR_RNDIS_MODE(R.string.RNDIS_MODE),
        STR_ETH_MODE(R.string.ETH_MODE),
        STR_IP_ADDRESS(R.string.IP_ADDRESS),
        STR_SUBNET_MASK(R.string.SUBNET_MASK),
        STR_GATEWAY(R.string.GATEWAY),
        STR_DNS_SERVER(R.string.DNS_SERVER),
        STR_AP_CONFIG(R.string.AP_CONFIG),
        STR_PAIR_WITH_WIFI_BASE_STATION(R.string.PAIR_WITH_WIFI_BASE_STATION),
        STR_CURRENT_STATUS(R.string.CURRENT_STATUS),
        STR_UNPAIRED(R.string.UNPAIRED),
        STR_PAIRED(R.string.PAIRED),
        STR_PAIR_BS_DETAILS(R.string.PAIR_BS_DETAILS),
        STR_OPEN_BLUETOOTH_SETTINGS(R.string.OPEN_BLUETOOTH_SETTINGS),
        STR_NEXT_LAN_CONFIG(R.string.NEXT_LAN_CONFIG),
        STR_TESTING_CONNECTIONS(R.string.TESTING_CONNECTIONS),
        STR_CONNECTING_TO_WIFI_NW(R.string.CONNECTING_TO_WIFI_NW),
        STR_CONNECTING_TO_NW(R.string.CONNECTING_TO_NW),
        STR_TESTING_CONN_TO_HOST(R.string.TESTING_CONN_TO_HOST),
        STR_CONFIG_TESTED_SUCCESS(R.string.CONFIG_TESTED_SUCCESS),
        STR_FINISH(R.string.FINISH),
        STR_RETRY_CONN(R.string.RETRY_CONN),
        STR_CHECK_CONFIG(R.string.CHECK_CONFIG),
        STR_WIFI_BASE_CONFIG(R.string.WIFI_BASE_CONFIG),
        STR_CURRENT_PROGRESS(R.string.CURRENT_PROGRESS),
        STR_PAIR(R.string.PAIR),
        STR_LAN(R.string.LAN),
        STR_AP(R.string.AP),
        STR_TEST_NL(R.string.TEST_NL),
        STR_SETUP_WIFI_BASE(R.string.SETUP_WIFI_BASE),
        STR_BLUETOOTH_SETTINGS(R.string.BLUETOOTH_SETTINGS),
        STR_INJECT_KEYS(R.string.INJECT_KEYS),
        STR_INPUT_SETTINGS(R.string.INPUT_SETTINGS),
        STR_RECEIPT_MERCHANT_COPY(R.string.RECEIPT_MERCHANT_COPY),
        STR_RECEIPT_CARD_HOLDER_COPY(R.string.RECEIPT_CARD_HOLDER_COPY),
        STR_DUPLICATE_RECEIPT(R.string.DUPLICATE_RECEIPT),
        STR_RECEIPT_SAF_RECORD(R.string.RECEIPT_SAF_RECORD),
        STR_RECEIPT_NOT_INVOICE(R.string.RECEIPT_NOT_INVOICE),
        STR_RECEIPT_VOID(R.string.RECEIPT_VOID),
        STR_RECEIPT_VOIDED_AT(R.string.RECEIPT_VOIDED_AT),
        STR_RECEIPT_NO(R.string.RECEIPT_NO),
        STR_MSG_NO(R.string.MSG_NO),
        STR_SESSION_NO(R.string.SESSION_NO),
        STR_AID(R.string.AID),
        STR_APP_PSN(R.string.APP_PSN),
        STR_DEFERRED(R.string.DEFERRED),
        STR_NOT_AUTHORISED(R.string.NOT_AUTHORISED),
        STR_UNABLE_TO_AUTHORISE(R.string.UNABLE_TO_AUTHORISE),
        STR_CALL_ISSUER(R.string.CALL_ISSUER),
        STR_CARD_BALANCE(R.string.CARD_BALANCE),
        STR_CTLS(R.string.CTLS),
        STR_CTLS_CONFIG(R.string.CTLS_CONFIG),
        STR_ICC(R.string.ICC),
        STR_KEYED(R.string.KEYED),
        STR_MSR(R.string.MSR),
        STR_PIN_VERIFIED(R.string.PIN_VERIFIED),
        STR_PLS_SIGN_BELOW(R.string.PLS_SIGN_BELOW),
        STR_VERIFIED_PIN_AND_SIGN(R.string.VERIFIED_PIN_AND_SIGN),
        STR_CARDHOLDER_SIGN(R.string.CARDHOLDER_SIGN),
        STR_VERIFIED_BY_SIGN(R.string.VERIFIED_BY_SIGN),
        STR_VERIFIED_BY_DEVICE(R.string.VERIFIED_BY_DEVICE),
        STR_CARDHOLDER_NOT_PRESENT(R.string.CARDHOLDER_NOT_PRESENT),
        STR_VERIFIED_BY_PIN(R.string.VERIFIED_BY_PIN),
        STR_NO_CARDHOLDER(R.string.NO_CARDHOLDER),
        STR_VERIFICATION(R.string.VERIFICATION),
        STR_NO_CARDHOLDER_VERIFICATION(R.string.NO_CARDHOLDER_VERIFICATION),
        STR_DEBIT_ACT_TEXT(R.string.DEBIT_ACT_TEXT),
        STR_CREDIT_ACT_TEXT(R.string.CREDIT_ACT_TEXT),
        STR_TOTAL_SHOWN(R.string.TOTAL_SHOWN),
        STR_DIAGNOSTIC_CODE(R.string.DIAGNOSTIC_CODE),
        STR_EMV_TAGS(R.string.EMV_TAGS),
        STR_EMV_CONFIG(R.string.EMV_CONFIG),
        STR_AIP(R.string.AIP),
        STR_CVR(R.string.CVR),
        STR_RESPONSE_CODE(R.string.RESPONSE_CODE),
        STR_DISCOUNT(R.string.DISCOUNT),
        STR_UNABLE_TO_PRINT_RECEIPT(R.string.UNABLE_TO_PRINT_RECEIPT),
        STR_POS_ID(R.string.POS_ID),
        STR_INVOICE_NO(R.string.INVOICE_NO),
        STR_PID(R.string.PID),
        STR_MID(R.string.MID),
        STR_APP_SEQ(R.string.APP_SEQ),
        STR_TID(R.string.TID),
        STR_CER(R.string.CER),
        STR_VIRTUAL_MID(R.string.VIRTUAL_MID),
        STR_VIRTUAL_TID(R.string.VIRTUAL_TID),
        STR_VIRTUAL_NAME(R.string.VIRTUAL_NAME),
        STR_RRN(R.string.RRN),
        STR_ACCOUNT(R.string.ACCOUNT),
        STR_UTI(R.string.UTI),
        STR_CONTACTLESS(R.string.CONTACTLESS),
        STR_KEYED_TEL_ORDER(R.string.KEYED_TEL_ORDER),
        STR_KEYED_MAIL_ORDER(R.string.KEYED_MAIL_ORDER),
        STR_SWIPED(R.string.SWIPED),
        STR_EXPIRY_DATE_FORMAT(R.string.EXPIRY_DATE_FORMAT),
        STR_APP_START_DATE_FORMAT(R.string.APP_START_DATE_FORMAT),
        STR_CRYPTOGRAM(R.string.CRYPTOGRAM),
        STR_CRYPTOGRAM_TYPE(R.string.CRYPTOGRAM_TYPE),
        STR_TVR(R.string.TVR),
        STR_TSI(R.string.TSI),
        STR_DATE(R.string.DATE),
        STR_TIME(R.string.TIME),
        STR_NAME(R.string.NAME),
        STR_USER_NAME(R.string.USER_NAME),
        STR_PLS_DEBIT_MY_ACT(R.string.PLS_DEBIT_MY_ACT),
        STR_PLS_CREDIT_MY_ACT(R.string.PLS_CREDIT_MY_ACT),
        STR_REV(R.string.REV),
        STR_PRE_AUTHORISATION(R.string.PRE_AUTHORISATION),
        STR_THIS_IS_NOT_DEBIT(R.string.THIS_IS_NOT_DEBIT),
        STR_FUND_AUTH_TEXT(R.string.FUND_AUTH_TEXT),
        STR_NO_CVM(R.string.NO_CVM),
        STR_SIG(R.string.SIG),
        STR_PIN_SIG(R.string.PIN_SIG),
        STR_MAN(R.string.MAN),
        STR_SWIPE(R.string.SWIPE),
        STR_NA(R.string.NA),
        STR_SN(R.string.SN),
        STR_NO_TRANS(R.string.NO_TRANS),
        STR_APPROVED(R.string.APPROVED),
        STR_PAN(R.string.PAN),
        STR_DEBITS(R.string.DEBITS),
        STR_CREDITS(R.string.CREDITS),
        STR_NET(R.string.NET),
        STR_FROM(R.string.FROM),
        STR_SESSION_TOTS_UNCONFIRMED(R.string.SESSION_TOTS_UNCONFIRMED),
        STR_PREVIOUS(R.string.PREVIOUS),
        STR_CURRENT(R.string.CURRENT),
        STR_TOTAL_NET(R.string.TOTAL_NET),
        STR_SESSION_TOTS_NOT_AGREED(R.string.SESSION_TOTS_NOT_AGREED),
        STR_END_OF_REPORT(R.string.END_OF_REPORT),
        STR_CURRENT_SESSION(R.string.CURRENT_SESSION),
        STR_DEPOSIT_REVERSAL(R.string.DEPOSIT_REVERSAL),
        STR_REFUND_REVERSAL(R.string.REFUND_REVERSAL),
        STR_DEBIT(R.string.DEBIT),
        STR_Z_BALANCES(R.string.Z_BALANCES),
        STR_TOTALS_RESET(R.string.TOTALS_RESET),
        STR_X_BALANCES(R.string.X_BALANCES),
        STR_TOTALS_NOT_SET(R.string.TOTALS_NOT_SET),
        STR_GRAND_TOTALS(R.string.GRAND_TOTALS),
        STR_TRANS_REC_FROM(R.string.TRANS_REC_FROM),
        STR_TO(R.string.TO),
        STR_FALLBACK(R.string.FALLBACK),
        STR_PLS_RETAIN_RECEIPTS(R.string.PLS_RETAIN_RECEIPTS),
        STR_Z_REPORT(R.string.Z_REPORT),
        STR_X_REPORT_RECEIPT(R.string.X_REPORT_RECEIPT),
        STR_CURRENCY(R.string.CURRENCY),
        STR_NET_TOTAL(R.string.NET_TOTAL),
        STR_INCLUSIVE_OF(R.string.INCLUSIVE_OF),
        STR_TILL_RECEIPT_INCLUSIVE_OF(R.string.TILL_RECEIPT_INCLUSIVE_OF),
        STR_REPORT_COMPLETE(R.string.REPORT_COMPLETE),
        STR_SETTLEMENT_SUCCESS(R.string.SETTLEMENT_SUCCESS),
        STR_SETTLEMENT_FAILURE(R.string.SETTLEMENT_FAILURE),
        STR_CARD_SCHEME_NET_TOTALS(R.string.CARD_SCHEME_NET_TOTALS),
        STR_SYS_INFO(R.string.SYS_INFO),
        STR_FIRMWARE_VER(R.string.FIRMWARE_VER),
        STR_PTID(R.string.PTID),
        STR_TERMINAL_SN(R.string.TERMINAL_SN),
        STR_MODEL(R.string.MODEL),
        STR_BATTERY_LEVEL(R.string.BATTERY_LEVEL),
        STR_EMV_ENABLED(R.string.EMV_ENABLED),
        STR_RECONCILIATION_TIME(R.string.RECONCILIATION_TIME),
        STR_NO_REC_PERFORMED(R.string.NO_REC_PERFORMED),
        STR_SOFTWARE_VER(R.string.SOFTWARE_VER),
        STR_CELLULAR_INFO(R.string.CELLULAR_INFO),
        STR_CELLULAR_NETWORK(R.string.CELLULAR_NETWORK),
        STR_BAND(R.string.BAND),
        STR_WIFI_INFO(R.string.WIFI_INFO),
        STR_LAST_Z_REPORT(R.string.LAST_Z_REPORT),
        STR_LAST_UPDATE_CHECK(R.string.LAST_UPDATE_CHECK),
        STR_APN_NAME(R.string.APN_NAME),
        STR_APN(R.string.APN),
        STR_AMT(R.string.AMT),
        STR_CBK(R.string.CBK),
        STR_TIP(R.string.TIP),
        STR_DISC(R.string.DISC),
        STR_TOT(R.string.TOT),
        STR_ABOUT_APPLICATION(R.string.ABOUT_APPLICATION),
        STR_CURRENT_SIM(R.string.CURRENT_SIM),
        STR_SIM1(R.string.SIM1),
        STR_SIM2(R.string.SIM2),
        STR_NO_RATES_DOWNLOADED(R.string.NO_RATES_DOWNLOADED),
        STR_TOTALS(R.string.TOTALS),
        STR_FULL_VERSION(R.string.FULL_VERSION),
        STR_SHORT_VERSION(R.string.SHORT_VERSION),
        STR_COUNT(R.string.COUNT),
        STR_SUB_TOTAL(R.string.SUB_TOTAL),
        STR_REC_NB(R.string.REC_NB),
        STR_SALE_REV(R.string.SALE_REV),
        STR_REFUND_REV(R.string.REFUND_REV),
        STR_CASH_REV(R.string.CASH_REV),
        STR_COMPLETION_REV(R.string.COMPLETION_REV),
        STR_PLS_AUTHORISE(R.string.PLS_AUTHORISE),
        STR_MY_ACCOUNT(R.string.MY_ACCOUNT),
        STR_PREAUTH_DECLARATION(R.string.PREAUTH_DECLARATION),
        STR_ETHERNET_SETTINGS(R.string.ETHERNET_SETTINGS),
        STR_ACCESS_MODE_GET_CARD_TAP_SWIPE_INSERT_TEXT(R.string.ACCESS_MODE_GET_CARD_TAP_SWIPE_INSERT_TEXT),
        STR_ACCESS_MODE_GET_CARD_TAP_SWIPE_TEXT(R.string.ACCESS_MODE_GET_CARD_TAP_SWIPE_TEXT),
        STR_ACCESS_MODE_GET_CARD_TAP_INSERT_TEXT(R.string.ACCESS_MODE_GET_CARD_TAP_INSERT_TEXT),
        STR_ACCESS_MODE_GET_CARD_SWIPE_INSERT_TEXT(R.string.ACCESS_MODE_GET_CARD_SWIPE_INSERT_TEXT),
        STR_ACCESS_MODE_GET_CARD_TAP_TEXT(R.string.ACCESS_MODE_GET_CARD_TAP_TEXT),
        STR_ACCESS_MODE_GET_CARD_SWIPE_TEXT(R.string.ACCESS_MODE_GET_CARD_SWIPE_TEXT),
        STR_ACCESS_MODE_GET_CARD_INSERT_TEXT(R.string.ACCESS_MODE_GET_CARD_INSERT_TEXT),
        STR_ACCESS_MODE_PIN_TEXT(R.string.ACCESS_MODE_PIN_TEXT),
        STR_ENTER_PIN_LAST_TRY(R.string.ENTER_PIN_LAST_TRY),
        STR_ENTER_PIN_TRY(R.string.ENTER_PIN_TRY),
        STR_VIEW_CARDHOLDER_COPY(R.string.VIEW_CARDHOLDER_COPY),
        STR_VIEW_MERCHANT_COPY(R.string.VIEW_MERCHANT_COPY),
        STR_MAIL_CARDHOLDER_COPY(R.string.MAIL_CARDHOLDER_COPY),
        STR_MAIL_MERCHANT_COPY(R.string.MAIL_MERCHANT_COPY),
        STR_PRINT_MERCHANT_COPY(R.string.PRINT_MERCHANT_COPY),
        STR_PRINT_BOTH(R.string.PRINT_BOTH),
        STR_PRINT(R.string.PRINT),
        STR_SELECT_RECEIPT(R.string.SELECT_RECEIPT),
        STR_ENTER_EMAIL(R.string.ENTER_EMAIL),
        STR_MERCHANT_EMAIL_QUEUED(R.string.EMAIL_QUEUED_MERCHANT),
        STR_CUSTOMER_EMAIL_QUEUED(R.string.EMAIL_QUEUED_CUSTOMER),
        STR_ERROR_EMAIL_FIELD_REQUIRED(R.string.ERROR_EMAIL_FIELD_REQUIRED),
        STR_DIGITAL_SIG(R.string.DIGITAL_SIG),
        STR_SELECT_ACCOUNT(R.string.SELECT_ACCOUNT),
        STR_SAV(R.string.SAV),
        STR_CHQ(R.string.CHQ),
        STR_CRD(R.string.CRD),
        STR_MENU_BUTTON(R.string.MENU_BUTTON ),
        STR_CUSTOMER_LOGO(R.string.CUSTOMER_LOGO ),
        STR_SPLASH_LOGO(R.string.SPLASH_LOGO),
        STR_RECEIPT_IMAGE(R.string.RECEIPT_IMAGE),
        STR_CANCEL_NL_RETURN_TO_MAIN_MENU(R.string.CANCEL_RETURN_MENU),
        STR_SETTLEMENT_REPORT(R.string.SETTLEMENT_REPORT),
        STR_PRE_SETTLEMENT_REPORT(R.string.PRE_SETTLEMENT_REPORT),
        STR_LAST_SETTLEMENT_REPORT(R.string.LAST_SETTLEMENT_REPORT),
        STR_SETTLEMENT_DATE_FORMAT(R.string.SETTLEMENT_DATE_FORMAT),
        STR_RECONCILIATIONS_LIST(R.string.RECONCILIATIONS_LIST),
        STR_RECONCILIATION_BR_VAR(R.string.RECONCILIATION_BR_VAR),
        STR_TRANS_ID_VAR(R.string.TRANS_ID_VAR),
        STR_BATCH_NUMBER_VAR(R.string.BATCH_NUMBER_VAR),
        STR_START_TRAN_VAR(R.string.START_TRAN_VAR),
        STR_END_TRAN_VAR(R.string.END_TRAN_VAR),
        STR_TOTAL_COUNT_VAR(R.string.TOTAL_COUNT_VAR),
        STR_TOTAL_AMOUNT_VAR(R.string.TOTAL_AMOUNT_VAR),
        STR_TOTALS_IN_BALANCE(R.string.TOTALS_IN_BALANCE),
        STR_TOTALS_OUT_OF_BALANCE(R.string.TOTALS_OUT_OF_BALANCE),
        STR_HOST_AUTO_SETTLED(R.string.HOST_AUTO_SETTLED),
        STR_SETTLEMENT_FAILED(R.string.SETTLEMENT_FAILED),
        STR_TERMINAL_SETTLED(R.string.TERMINAL_SETTLED),
        STR_SYSTEM_ERROR(R.string.SYSTEM_ERROR),
        STR_TOTALS_NOT_RESET(R.string.TOTALS_NOT_RESET),
        STR_LOGON( R.string.LOGON ),
        STR_RSA_LOGON( R.string.RSA_LOGON ),
        STR_LOGON_FAILED( R.string.LOGON_FAILED ),
        STR_ATC(R.string.ATC),
        STR_SURCHARGES( R.string.SURCHARGES ),
        STR_SIG_REQUIRED( R.string.SIG_REQUIRED ),
        STR_WOW_MID( R.string.WOW_MID ),
        STR_WOW_TID( R.string.WOW_TID ),
        STR_WOW_CARD( R.string.WOW_CARD ),
        STR_EXPIRES( R.string.EXPIRES ),
        STR_WOW_AID( R.string.WOW_AID ),
        STR_WOW_TVR(R.string.WOW_TVR),
        STR_WOW_PURCHASE( R.string.WOW_PURCHASE ),
        STR_WOW_REFUND( R.string.WOW_REFUND ),
        STR_WOW_DEPOSIT( R.string.WOW_DEPOSIT ),
        STR_WOW_CASHOUT( R.string.WOW_CASHOUT ),
        STR_WOW_TIP( R.string.WOW_TIP ),
        STR_WOW_SURCHARGE( R.string.WOW_SURCHARGE ),
        STR_WOW_TOTAL( R.string.WOW_TOTAL ),
        STR_WOW_APPROVED( R.string.WOW_APPROVED ),
        STR_WOW_DECLINED( R.string.WOW_DECLINED ),
        STR_WOW_CANCELLED( R.string.WOW_CANCELLED ),
        STR_WOW_SAVINGS( R.string.WOW_SAVINGS ),
        STR_WOW_CHEQUE( R.string.WOW_CHEQUE ),
        STR_WOW_CREDIT( R.string.WOW_CREDIT ),
        STR_PLB_RESTRICTED_ITEM(R.string.PLB_RESTRICTED_ITEM ),
        STR_SELECT_APPLICATION(R.string.SELECT_APPLICATION),
        STR_RECEIPT_POWERED_BY_WPAY(R.string.RECEIPT_POWERED_BY_WPAY),
        STR_MOTO(R.string.MOTO),
        STR_CLEAR_REVERSALS(R.string.CLEAR_REVERSALS),
        STR_NO_TRANS_TO_REVERSED(R.string.NO_TRANS_TO_REVERSED),
        STR_REVERSALS_CLEARED(R.string.REVERSALS_CLEARED),
        STR_REFUND_MOTO_AUTO(R.string.REFUND),
        STR_WOW_PREAUTH(R.string.WOW_PREAUTH),
        STR_WOW_REVERSAL(R.string.WOW_REVERSAL),
        STR_WOW_COMPLETION(R.string.WOW_COMPLETION),
        STR_PREAUTH_NOT_FOUND(R.string.PREAUTH_NOT_FOUND),
        STR_PREAUTH_NOT_FOUND_TRY_AGAIN(R.string.PREAUTH_NOT_FOUND_TRY_AGAIN),
        STR_RFN_NOT_ENTERED(R.string.RFN_NOT_ENTERED),
        STR_AMT_EXCEEDS_PREAUTH_AMT(R.string.AMT_EXCEEDS_PREAUTH_AMT),
        STR_PREAUTH_EXISTS(R.string.PREAUTH_EXISTS),
        STR_WOW_PREAUTH_CANCELLATION(R.string.WOW_PREAUTH_CANCELLATION),
        STR_PREAUTH_WAS_CANCELLED(R.string.PREAUTH_WAS_CANCELLED),
        STR_WOW_AUTH_CODE(R.string.WOW_AUTH_CODE),
        STR_IS_CARDHOLDER_PRESENT(R.string.IS_CARDHOLDER_PRESENT),
        STR_CONFIRM_SURCHARGE(R.string.CONFIRM_SURCHARGE),
        STR_VAR_SURCHARGE_APPLIED_NL_CONTINUE(R.string.VAR_SURCHARGE_APPLIED_NL_CONTINUE),
        STR_SAF_VIEW_AND_CLEAR(R.string.SAF_VIEW_AND_CLEAR),
        STR_SAF_RECORD_DELETE(R.string.SAF_RECORD_DELETE),
        STR_SAF_RECORD_DELETED(R.string.SAF_RECORD_DELETED),
        STR_RECORD_UNABLE_TO_READ(R.string.RECORD_UNABLE_TO_READ),
        STR_ONLY_CREDIT_ACCOUNT_ALLOWED(R.string.ONLY_CREDIT_ACCOUNT_ALLOWED),
        STR_TMS_LOGON(R.string.TMS_LOGON),
        STR_GRANT_ADMIN_MENU_ACCESS(R.string.GRANT_ADMIN_MENU_ACCESS),

        STR_PRE_AUTH_SEARCH_AND_VIEW(R.string.PRE_AUTH_SEARCH_AND_VIEW),
        STR_LIST_PRE_AUTH(R.string.LIST_PRE_AUTH),
        STR_PRE_AUTH_SEARCH_AND_VIEW_SELECT_DATE(R.string.PRE_AUTH_SEARCH_AND_VIEW_SELECT_DATE),
        STR_ENTER_RRN(R.string.ENTER_RRN),
        STR_MCR_INDICATOR(R.string.MCR_INDICATOR),
        STR_SALE_MOTO(R.string.SALE_MOTO),
        STR_REFUND_MOTO(R.string.REFUND_MOTO),
        STR_INITIATE_RKI(R.string.INITIATE_RKI),
        STR_USER_IS_LOCKED_TOO_MANY_PASSCODE_ATTEMPTS(R.string.USER_IS_LOCKED_TOO_MANY_PASSCODE_ATTEMPTS),
        STR_TOTAL_COLON( R.string.TOTAL_COLON ),
        STR_CONFIRM_CANCEL(R.string.CONFIRM_CANCEL),
        STR_DECLINED_UPPER(R.string.DECLINED_UPPER),
        STR_AAC_LABEL(R.string.AAC_LABEL),
        STR_TC_LABEL(R.string.TC_LABEL),
        STR_ARQC_LABEL(R.string.ARQC_LABEL),
        STR_TOTAL_OFFLINE_TRANS_AMOUNT_LIMIT_EXCEEDED(R.string.TOTAL_OFFLINE_TRANS_AMOUNT_LIMIT_EXCEEDED),
        STR_OFFLINE_TRANS_AMOUNT_LIMIT_EXCEEDED(R.string.OFFLINE_TRANS_AMOUNT_LIMIT_EXCEEDED),
        STR_OFFLINE_TRANS_COUNT_LIMIT_EXCEEDED(R.string.OFFLINE_TRANS_COUNT_LIMIT_EXCEEDED),
        STR_OFFLINE_TRANS_CLOSE_TO_LIMIT(R.string.OFFLINE_TRANS_CLOSE_TO_LIMIT),
        STR_REFUND_LIMIT_EXCEEDED(R.string.REFUND_LIMIT_EXCEEDED),
        STR_REFUND_COUNT_LIMIT_EXCEEDED(R.string.REFUND_COUNT_LIMIT_EXCEEDED),
        STR_CDO_INDICATOR(R.string.CDO_INDICATOR),
        STR_TRANSACTION_HISTORY(R.string.TRANSACTION_HISTORY),
        STR_CARD_NOT_PRESENTED(R.string.CARD_NOT_PRESENTED),
        STR_NUMBER_TRANSACTIONS(R.string.ENTER_NUM_TRANSACTIONS),
        STR_NUMBER_KEY_ITERATIONS(R.string.ENTER_NUM_KEY_ITERATIONS),
        STR_RECEIPT_DEMO_MODE(R.string.RECEIPT_DEMO_MODE),
        STR_CLEAR_TRANSACTIONS(R.string.CLEAR_TRANSACTIONS),
        STR_SETTLEMENT(R.string.SETTLEMENT),
        STR_PRE_SETTLEMENT(R.string.PRE_SETTLEMENT),
        STR_LAST_SETTLEMENT(R.string.LAST_SETTLEMENT),
        STR_NET_MSG(R.string.NET_MSG),
        STR_NET_TOTAL_MSG(R.string.NET_TOTAL_MSG),
        STR_NET_TOTALS(R.string.NET_TOTALS),
        STR_NO_RESPONSE(R.string.NO_RESPONSE),
        STR_NO_RESPONSE_PLEASE_TRY_AGAIN(R.string.NO_RESPONSE_PLEASE_TRY_AGAIN),
        STR_CONFIRM_RESET_LOCAL_APP_SETTINGS(R.string.CONFIRM_RESET_APP_SETTINGS),
        STR_LOCAL_APP_SETTINGS_RESET(R.string.APP_SETTINGS_RESET),
        STR_MOBILE_COMMS_FALLBACK(R.string.MOBILE_COMMS_FALLBACK),
        STR_COMMS_LOOP_TEST(R.string.COMMS_LOOP_TEST),
        STR_DUKPT_TEST(R.string.DUKPT_TEST),
        STR_PRINT_CUSTOMER_RECEIPT(R.string.PRINT_CUSTOMER_RECEIPT),
        STR_EMPTY_STR(R.string.EMPTY_STRING),
        STR_TIP_TOTALS(R.string.TIP_TOTALS),
        STR_SURCHARGE_TOTALS(R.string.SURCHARGE_TOTALS),
        STR_PURCH(R.string.PURCH),
        STR_REFUNDS(R.string.REFUNDS),
        STR_NET_AMOUNT(R.string.NET_AMOUNT),
        STR_PURCH_COUNT(R.string.PURCH_COUNT),
        STR_PURCH_AMOUNT(R.string.PURCH_AMOUNT),
        STR_CASH_COUNT(R.string.CASH_COUNT),
        STR_CASH_AMOUNT(R.string.CASH_AMOUNT),
        STR_REFUND_COUNT(R.string.REFUND_COUNT),
        STR_REFUND_AMOUNT(R.string.REFUND_AMOUNT),
        STR_CARD_TYPE_TOTALS(R.string.CARD_TYPE_TOTALS),
        STR_PURCH_CAPS(R.string.PURCH_CAPS),
        STR_REFUNDS_CAPS(R.string.REFUNDS_CAPS),
        STR_CASH_CAPS(R.string.CASH_CAPS),
        STR_ENQUIRY_FAILED(R.string.ENQUIRY_FAILED),
        STR_SETTLED(R.string.SETTLED),
        STR_TILL_RECEIPT_ALREADY_SETTLED_MESSAGE(R.string.TILL_RECEIPT_ALREADY_SETTLED_MESSAGE),
        STR_SHIFT_TOTALS_MENU(R.string.SHIFT_TOTALS_MENU),
        STR_SHIFT_TOTALS(R.string.SHIFT_TOTALS),
        STR_SUB_TOTALS(R.string.SUB_TOTALS),
        STR_REPRINT_SHIFT_TOTALS(R.string.REPRINT_SHIFT_TOTALS),
        STR_EXCLUDING_SURCHARGE(R.string.EXCLUDING_SURCHARGE),
        STR_TOTALS_REPRINT(R.string.TOTALS_REPRINT),
        STR_CONFIRM_RESET_TOTALS_SETTINGS(R.string.CONFIRM_RESET_TOTALS_SETTINGS),
        STR_TOTALS_SETTINGS_RESET( R.string.TOTALS_SETTINGS_RESET),
        STR_TOTALS_SETTINGS(R.string.TOTALS_SETTINGS),
        STR_KEY_INJECTION_REQUIRED(R.string.KEY_INJECTION_REQUIRED),

        // Place any new enum above this
        STR_EMPTY(0);

        private final int id;
        String_id( int id) { this.id = id; }
        public int getId() { return id; }
    }

    boolean getLedOne();
    boolean getLedTwo();
    boolean getLedThree();
    boolean getLedFour();
}
