package com.linkly.libui;

import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_ACCESS_APP_SELECTION;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_ADD_TIP;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_ANIMATED_PRINT;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_BLANK;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_DEFERRED_AUTHS;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_GET_CARD;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_INFORMATION;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_INPUT;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_INPUT_AMOUNT;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_INPUT_AMOUNT_IDLE;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_LOYALTY_POST_AMOUNT_ENTRY;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_LOYALTY_POST_CARD_PRESENTED;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_LOYALTY_POST_TRANSACTION;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_PICK_GRATUITY;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_PRE_AUTH_SEARCH_AND_VIEW;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_PRE_AUTH_SEARCH_AND_VIEW_SELECT_DATE;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_QR_CODE;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_QR_SCAN;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_QUESTION;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_REBOOT;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_SAF_VIEW_AND_CLEAR;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_SCREEN_PRINT;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_SELECT_ACCOUNT;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_SELECT_APPLICATION;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_SIG;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_TABLE;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_TRANSACTION_HISTORY;
import static com.linkly.libui.IUIDisplay.ACTIVITY_ID.ACT_USER_LOGIN;
import static com.linkly.libui.IUIDisplay.EXTRA_LONG_TIMEOUT;
import static com.linkly.libui.IUIDisplay.FOUR_SEC_TIMEOUT;
import static com.linkly.libui.IUIDisplay.IMMEDIATE_TIMEOUT;
import static com.linkly.libui.IUIDisplay.INFO_TIMEOUT;
import static com.linkly.libui.IUIDisplay.LONG_TIMEOUT;
import static com.linkly.libui.IUIDisplay.MAX_TIMEOUT;
import static com.linkly.libui.IUIDisplay.NO_TIMEOUT;
import static com.linkly.libui.IUIDisplay.ONE_SEC_TIMEOUT;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.ERROR_ICON;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.ERROR_ICON_WITH_BEEP;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.INFO_ICON;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.NO_ICON;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.PRINTING_ICON;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.PROCESSING_ICON;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.PROCESSING_ICON_STILL;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.SUCCESS_ICON;
import static com.linkly.libui.IUIDisplay.SCREEN_ICON.WARNING_ICON;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_CDCVM;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_CTLS;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_CTLS_MAN;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_CTLS_MSR;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_ICC;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_ICC_CTLS;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_ICC_MAN;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_ICC_MSR;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_MAN;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_MAN_CTLS_ICC;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_MSR;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_MSR_ICC_CTLS;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_MSR_ICC_CTLS_MAN;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_MSR_ICC_MAN;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_MSR_MAN;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_CARD_MSR_MAN_CTLS;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_INPUT_ALPHA_NUMERIC;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_INPUT_EMAIL;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_INPUT_NUMBER;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_INPUT_NUMBER_PASSWORD;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_INPUT_NUMERIC_ALPHA_NO_SYM;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.GET_INPUT_PASSWORD;
import static com.linkly.libui.IUIDisplay.SCREEN_ID.NOT_SET;
import static com.linkly.libui.IUIDisplay.SHORT_TIMEOUT;
import static com.linkly.libui.IUIDisplay.String_id.*;
import static com.linkly.libui.IUIDisplay.THREE_SEC_TIMEOUT;

import com.linkly.libui.IUIDisplay.ACTIVITY_ID;
import com.linkly.libui.IUIDisplay.SCREEN_ICON;
import com.linkly.libui.IUIDisplay.SCREEN_ID;
import com.linkly.libui.IUIDisplay.String_id;

public enum UIScreenDef {
    // UIScreenDef(SCREEN_ID screenId, SCREEN_ICON screenIcon, String_id titleId, String_id promptId, boolean block )
    CARD_TYPE_NOT_ALLOWED(NOT_SET, ERROR_ICON, STR_EMPTY, STR_CARD_TYPE_NOT_ALLOWED, SHORT_TIMEOUT, true),

    // special cases for loyalty app integration
    LOYALTY_APP_POST_AMOUNT_ENTRY(ACT_LOYALTY_POST_AMOUNT_ENTRY, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, MAX_TIMEOUT, DEFAULT_VALUES.DISMISSIBLE, DEFAULT_VALUES.BLOCK, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN),
    LOYALTY_APP_POST_CARD_PRESENTED(ACT_LOYALTY_POST_CARD_PRESENTED, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, MAX_TIMEOUT, DEFAULT_VALUES.DISMISSIBLE, DEFAULT_VALUES.BLOCK, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN),
    LOYALTY_APP_POST_TRANSACTION(ACT_LOYALTY_POST_TRANSACTION, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, MAX_TIMEOUT, DEFAULT_VALUES.DISMISSIBLE, DEFAULT_VALUES.BLOCK, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN),


    // SCREEN_DEF(ACTIVITY_ID id, SCREEN_ID screenId, SCREEN_ICON screenIcon, String_id titleId, String_id promptId )
    CARD_NOT_READ_PROP(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_CARD_NOT_READ_PROP),
    OFFLINE_TRANS_NOT_ALLOW(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_OFFLINE_TRANS_NOT_ALLOW),
    TERMINAL_NOT_CONFIGURED(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_TERMINAL_NOT_CONFIGURED),
    DATABASE_FULL(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_DATABASE_FULL),
    ATM_ONLY(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_ATM_ONLY),
    INSERT_CARD(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_INSERT_CARD),
    CASH_NOT_ALLOW(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_CASH_NOT_ALLOW),
    CASH_ONLY_CARD(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_CASH_ONLY_CARD),
    CANCELLED(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_CANCELLED),
    COMPLETION_AMOUNT_CHECK(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_COMPLETION_AMOUNT_CHECK),
    TOTAL_AMOUNT_TOO_LARGE(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_TOTAL_AMOUNT_TOO_LARGE),
    CASHBACK_TOO_LARGE(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_CASHBACK_TOO_LARGE),
    TRANS_NOT_ALLOWED(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_TRANS_NOT_ALLOWED),
    TRANS_CANCEL(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_TRANS_CANCEL),
    CTLS_NOT_ENABLED(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_CTLS_NOT_ENABLED),
    ADDITIONAL_RESPONSE_VAR(NOT_SET, ERROR_ICON, STR_EMPTY, STR_VAR, SHORT_TIMEOUT, true),
    PAPER_OUT(ERROR_ICON, STR_ERROR, STR_PAPER_OUT, SHORT_TIMEOUT, true),
    BATTERY_TOO_LOW(ERROR_ICON, STR_ERROR, STR_BATTERY_TOO_LOW, SHORT_TIMEOUT, true),
    INVALID_RECEIPT_NUMBER(ERROR_ICON, STR_REVERSAL, STR_INVALID_RECEIPT_NUMBER, SHORT_TIMEOUT, true),
    INVALID_AMOUNT(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_REVERSAL, STR_INVALID_AMOUNT),
    UNABLE_TO_REVERSE_TOO_OLD(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_REVERSAL, STR_UNABLE_TO_REVERSE_TOO_OLD),
    UNABLE_TO_REVERSE(ERROR_ICON, STR_REVERSAL, STR_UNABLE_TO_REVERSE, SHORT_TIMEOUT, true),
    ALREADY_REVERSED(ERROR_ICON, STR_REVERSAL, STR_ALREADY_REVERSED, SHORT_TIMEOUT, true),
    TRANSACTION_TYPE_CANT_BE_REVERSED(ERROR_ICON, STR_REVERSAL, STR_TRANSACTION_TYPE_CANT_BE_REVERSED, SHORT_TIMEOUT, true),
    NO_TRANSACTION_FOUND(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_REVERSAL, STR_NO_TRANSACTION_FOUND),
    DUPLICATE_SESSION(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_DUPLICATE_SESSION),
    CANT_FIND_THE_LATEST(ERROR_ICON, STR_REVERSAL, STR_CANT_FIND_THE_LATEST, SHORT_TIMEOUT, true),
    CANT_REVERSE_A_REFUND(ERROR_ICON, STR_REVERSAL, STR_CANT_REVERSE_A_REFUND, SHORT_TIMEOUT, true),
    CANT_REVERSE_OFFLINE_AN_ONLINE_APPROVED_TRANS(ERROR_ICON, STR_REVERSAL, STR_CANT_REVERSE_OFFLINE_AN_ONLINE_APPROVED_TRANS, SHORT_TIMEOUT, true),

    ACT_BLANK_SCREEN(ACT_BLANK, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY),
    ACT_REBOOT_SCREEN(ACT_REBOOT, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY),
    DATABASE_STATS(ACT_TABLE, NOT_SET, NO_ICON, STR_DATABASE_STATS, STR_EMPTY),
    TRANSACTION_LIST(ACT_TABLE, NOT_SET, NO_ICON, STR_TRANSACTION_LIST, STR_EMPTY),
    TRANSACTION_DETAILS(ACT_TABLE, NOT_SET, NO_ICON, STR_TRANSACTION_DETAILS, STR_EMPTY),
    RECONCILIATION_LIST(ACT_TABLE, NOT_SET, NO_ICON, STR_RECONCILIATIONS_LIST, STR_EMPTY),
    ENTER_CASHBACK(ACT_INPUT_AMOUNT, NOT_SET, NO_ICON, STR_EMPTY, STR_CASHBACK),
    ENTER_TOTAL_SALE_VAR(ACT_INPUT_AMOUNT, NOT_SET, NO_ICON, STR_EMPTY, STR_ENTER_TOTAL_SALE_VAR),
    ENTER_TIP_SALE_VAR(ACT_INPUT_AMOUNT, NOT_SET, NO_ICON, STR_EMPTY, STR_ENTER_TIP_SALE_VAR),
    ACT_QR_CODE_SCREEN(ACT_QR_CODE, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY),
    ACT_QR_SCAN_SCREEN(ACT_QR_SCAN, NOT_SET, NO_ICON, STR_SCAN_QR, STR_EMPTY),
    ENTER_SUPERVISOR_PASSWORD(ACT_USER_LOGIN, NOT_SET, NO_ICON, STR_AUTH_REQUIRED, STR_ENTER_SUPERVISOR_PASSWORD, STR_EMPTY, DEFAULT_VALUES.MIN_USERNAME_LEN, DEFAULT_VALUES.MAX_USERNAME_LEN),
    GET_CARD_CDCVM_SCREEN(ACT_GET_CARD, GET_CARD_CDCVM, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_MAN_SCREEN(ACT_GET_CARD, GET_CARD_MAN, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_ICC_SCREEN(ACT_GET_CARD, GET_CARD_ICC, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_CTLS_SCREEN(ACT_GET_CARD, GET_CARD_CTLS, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_MSR_SCREEN(ACT_GET_CARD, GET_CARD_MSR, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_ICC_MAN_SCREEN(ACT_GET_CARD, GET_CARD_ICC_MAN, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_ICC_CTLS_SCREEN(ACT_GET_CARD, GET_CARD_ICC_CTLS, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_ICC_MSR_SCREEN(ACT_GET_CARD, GET_CARD_ICC_MSR, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_CTLS_MAN_SCREEN(ACT_GET_CARD, GET_CARD_CTLS_MAN, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_CTLS_MSR_SCREEN(ACT_GET_CARD, GET_CARD_CTLS_MSR, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_MSR_MAN_SCREEN(ACT_GET_CARD, GET_CARD_MSR_MAN, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_MSR_ICC_MAN_SCREEN(ACT_GET_CARD, GET_CARD_MSR_ICC_MAN, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_MSR_ICC_CTLS_SCREEN(ACT_GET_CARD, GET_CARD_MSR_ICC_CTLS, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_MSR_MAN_CTLS_SCREEN(ACT_GET_CARD, GET_CARD_MSR_MAN_CTLS, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_MAN_CTLS_ICC_SCREEN(ACT_GET_CARD, GET_CARD_MAN_CTLS_ICC, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_CARD_MSR_ICC_CTLS_MAN_SCREEN(ACT_GET_CARD, GET_CARD_MSR_ICC_CTLS_MAN, NO_ICON, STR_EMPTY, STR_EMPTY),
    ACT_QUESTION_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY),
    ACT_INPUT_SCREEN(ACT_INPUT, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY),
    SETTLEMENT_SUCCESS(SUCCESS_ICON, STR_SETTLEMENT, STR_SETTLEMENT_SUCCESS,LONG_TIMEOUT,false),
    SETTLEMENT_TERMINAL_SETTLED(ERROR_ICON, STR_SETTLEMENT, STR_TERMINAL_SETTLED,LONG_TIMEOUT,false),
    AUTHORISED_VAR(ACT_INFORMATION, NOT_SET, SUCCESS_ICON, STR_EMPTY, STR_AUTHORISED_VAR),
    NL_AUTHORISED(ACT_INFORMATION, NOT_SET, SUCCESS_ICON, STR_EMPTY, STR_NL_AUTHORISED),
    NL_AUTHORISED_WITH_SIGN( ACT_INFORMATION, NOT_SET, SUCCESS_ICON, STR_EMPTY, STR_NL_AUTHORISED_WITH_SIG ),
    DECLINED_VAR(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_DECLINED_VAR),
    DECLINED(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_DECLINED),
    VAR_AMT_NL_VAR_NL_EXCEEDS_LIMITS_VAR(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_VAR_AMT_NL_VAR_NL_EXCEEDS_LIMITS_VAR),
    COMMS_FAILURE_VAR_RESPONSE_BR(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_COMMS_FAILURE_VAR_RESPONSE_BR),
    NEW_USER_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_NEW_USER, STR_GRANT_SUPERVISOR_PERMISSIONS),
    NEW_USER_ADMIN_SCREEN( ACT_QUESTION, NOT_SET, NO_ICON, STR_NEW_USER, STR_GRANT_ADMIN_MENU_ACCESS ),
    DEFERRED_AUTH_DECLINED(ACT_QUESTION, NOT_SET, NO_ICON, STR_BATCH_UPLOAD, STR_DEFERED_AUTH_DECLINED),

    DELETE_USER_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_DELETE_USER, STR_ARE_YOU_SURE_YOU_WANT_TO_DELETE),
    CONFIRM_CANCEL_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_CANCEL, STR_CONFIRM_CANCEL),
    CHOOSE_DEPT_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_DEPARTMENT, STR_PLEASE_CHOOSE),
    REMOVE_MERCHANT_COPY(ACT_QUESTION, NOT_SET, NO_ICON, STR_PRINTING, STR_REMOVE_MERCHANT_COPY),
    REMOVE_CARDHOLDER_COPY(ACT_QUESTION, NOT_SET, NO_ICON, STR_PRINTING, STR_REMOVE_CARDHOLDER_COPY),
    IS_SIGN_REQUIRED(ACT_QUESTION, NOT_SET, NO_ICON, STR_EMPTY, STR_IS_SIGN_REQUIRED),
    IS_CASH_BACK_NL_REQUIRED_NL_NL(ACT_QUESTION, NOT_SET, NO_ICON, STR_EMPTY, STR_IS_CASH_BACK_NL_REQUIRED_NL_NL),
    DO_ADD_GRATUITY(ACT_ADD_TIP, NOT_SET, NO_ICON, STR_EMPTY, STR_DO_ADD_GRATUITY),
//    DO_ADD_GRATUITY(ACT_QUESTION, NOT_SET, NO_ICON, STR_EMPTY, STR_DO_ADD_GRATUITY),
    SALE_GRATUITY_CASHBACK_TOTAL_CORRECT_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_SUMMARY, STR_SALE_VAR_NL_GRATUITY_VAR_NL_CASH_BACK_VAR_NL_TOTAL_VAR_NL_CORRECT),
    SALE_GRATUITY_TOTAL_CORRECT_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_SUMMARY, STR_SALE_VAR_NL_GRATUITY_VAR_NL_TOTAL_VAR_NL_CORRECT),
    SELECT_OPTION(ACT_QUESTION, NOT_SET, NO_ICON, STR_REVERSAL_UPLOAD, STR_SELECT_OPTION),
    APP_SELECTION(ACT_SELECT_APPLICATION, NOT_SET, NO_ICON, STR_SALE, STR_APP_SELECTION),
    APP_SELECTION_ACCESS_MODE(ACT_ACCESS_APP_SELECTION, NOT_SET, NO_ICON, STR_APP_SELECTION, STR_EMPTY),
    SELECT_ACCOUNT(ACT_SELECT_ACCOUNT, NOT_SET, NO_ICON, STR_SALE, STR_SELECT_ACCOUNT),
//    SELECT_ACCOUNT(ACT_QUESTION, NOT_SET, NO_ICON, STR_SALE, STR_SELECT_ACCOUNT),
    GRATUITY_SCREEN(ACT_PICK_GRATUITY, NOT_SET, NO_ICON, STR_GRATUITY, STR_EMPTY),
//    GRATUITY_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_GRATUITY, STR_EMPTY),
    PLEASE_CHOOSE_SALE(ACT_QUESTION, NOT_SET, NO_ICON, STR_SALE, STR_PLEASE_CHOOSE),
    PLEASE_CHOOSE_REVERSAL(ACT_QUESTION, NOT_SET, NO_ICON, STR_REVERSAL, STR_PLEASE_CHOOSE),
    WHICH_COPY_IS_REQUIRED(ACT_QUESTION, NOT_SET, NO_ICON, STR_REPRINT, STR_WHICH_COPY_IS_REQUIRED),
    DAILY_BATCH_REPORT_SELECT_TYPE(ACT_QUESTION, NOT_SET, NO_ICON, STR_DAILY_BATCH_REPORT, STR_SELECT_TYPE),
    PLEASE_CHOOSE_CARD_NOT_PRESENT(ACT_QUESTION, NOT_SET, NO_ICON, STR_CARD_NOT_PRESENT, STR_PLEASE_CHOOSE),
    PLEASE_CHOOSE_ACCOUNT_TYPE(ACT_QUESTION, NOT_SET, NO_ICON, STR_ACCOUNT_TYPE, STR_PLEASE_CHOOSE),
    TOTALS_REPORT_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_TOTALS_REPORT, STR_EMPTY),
    STR_CLEAR_TOTALS_SCREEN(ACT_QUESTION, NOT_SET, NO_ICON, STR_TOTALS_REPORT, STR_CLEAR_TOTALS),
    CONFIRM_SURCHARGE_OKAY(ACT_ADD_TIP, NOT_SET, NO_ICON, STR_CONFIRM_SURCHARGE, STR_VAR_SURCHARGE_APPLIED_NL_CONTINUE ),
    PRINT_CUSTOMER_RECEIPT(ACT_QUESTION, NOT_SET, NO_ICON, STR_PRINTING, STR_PRINT_CUSTOMER_RECEIPT),

    // SCREEN_DEF(ACTIVITY_ID id, SCREEN_ICON screenIcon, String_id titleId, String_id promptId, boolean dismissible)
    ACT_INFORMATION_SCREEN(ACT_INFORMATION, PROCESSING_ICON, STR_PROCESSING, STR_EMPTY, false),
    ACT_PROCESSING_LOYALTY(ACT_INFORMATION, PROCESSING_ICON, STR_CHECKING_LOYALTY, STR_EMPTY, false),
    ACT_PROCESSING_LOYALTY_CTLS(SUCCESS_ICON, STR_EMPTY, STR_PROCESSING_LOYALTY_CTLS, SHORT_TIMEOUT, true),

    CONNECTING_TO_HOST_SENDING_MSG(ACT_INFORMATION, PROCESSING_ICON, STR_CONNECTING_TO_HOST, STR_SENDING_MSG_BR, false),
    CONNECTING_TO_HOST_WAITING_FOR_RESPONSE(ACT_INFORMATION, PROCESSING_ICON, STR_CONNECTING_TO_HOST, STR_WAITING_FOR_RESPONSE_BR, false),
    COMMS_FAILURE_RECEIVING_RESPONSE(ACT_INFORMATION, ERROR_ICON, STR_COMMS_FAILURE, STR_RECEIVING_RESPONSE_BR, true),
    INPUT_TOO_LOW_TRY_AGAIN(ACT_INFORMATION, ERROR_ICON, STR_TOTAL_TOO_LOW, STR_TRY_AGAIN, true),
    PERMISSIONS_ERROR_SUPERVISOR_LOGIN(ACT_INFORMATION, ERROR_ICON, STR_PERMISSIONS_ERROR, STR_SUPERVISOR_LOGIN, true),
    INVALID_CARD_NUMBER_RE_ENTER(ACT_INFORMATION, ERROR_ICON, STR_INVALID_CARD_NUMBER, STR_RE_ENTER, true),
    CONNECTING_TO_HOST_PLEASE_WAIT(ACT_INFORMATION, PROCESSING_ICON, STR_CONNECTING_TO_HOST, STR_PLEASE_WAIT_BR, false),
    CONNECTING_TO_HOST_1_PLEASE_WAIT(ACT_INFORMATION, PROCESSING_ICON, STR_CONNECTING_TO_HOST_1, STR_PLEASE_WAIT_BR, false),
    CONNECTING_TO_HOST_2_PLEASE_WAIT(ACT_INFORMATION, PROCESSING_ICON, STR_CONNECTING_TO_HOST_2, STR_PLEASE_WAIT_BR, false),
    // MW: Note that when the screen name has the word trans in it & titleId is empty, it means that we are using displayId field to populate titleId
    PROCESSING_TRANS_PLEASE_WAIT(ACT_INFORMATION, PROCESSING_ICON, STR_EMPTY, STR_PROC_TRANS_PLEASE_WAIT_BR, false),
    PROCESSING_TRANS_PLEASE_WAIT_1(ACT_INFORMATION, PROCESSING_ICON, STR_EMPTY, STR_PROC_TRANS_PLEASE_WAIT_BR_1, false),
    PROCESSING_TRANS_PLEASE_WAIT_2(ACT_INFORMATION, PROCESSING_ICON, STR_EMPTY, STR_PROC_TRANS_PLEASE_WAIT_BR_2, false),
    TRANS_NOT_IMPLEMENTED(ACT_INFORMATION, WARNING_ICON, STR_EMPTY, STR_NOT_IMPLEMENTED, true),
    TRANS_DATA_FAILURE_RESPONSE_INVALID(ACT_INFORMATION, ERROR_ICON, STR_EMPTY, STR_DATA_FAILURE_RESPONSE_INVALID_BR, true),
    TRANS_COMMS_FAILURE_RESPONSE_INVALID(ACT_INFORMATION, ERROR_ICON, STR_EMPTY, STR_COMMS_FAILURE_RESPONSE_INVALID_BR, true),
    TRY_CONTACT_TRANS(ACT_INFORMATION, ERROR_ICON, STR_EMPTY, STR_TRY_CONTACT_TRANS, true),
    TRY_INSERT_SWIPE_OTHER_TRANS(ACT_INFORMATION, ERROR_ICON, STR_EMPTY, STR_TRY_INSERT_SWIPE_OTHER, true),

    WALLET_TRANS_NOT_ALLOWED_TRY_ANOTHER(ACT_INFORMATION, ERROR_ICON, STR_EMPTY, STR_WALLET_TRANS_NOT_ALLOWED_TRY_ANOTHER, true),
    AMOUNT_TOO_SMALL(ACT_INFORMATION, ERROR_ICON, STR_AMOUNT_TOO_SMALL, STR_MINIMUM_VAR_BR, true),
    AMOUNT_TOO_LARGE(ACT_INFORMATION, ERROR_ICON, STR_AMOUNT_TOO_LARGE, STR_MAXIMUM_VAR_BR, true),
    MAG_CARD_READ_ERROR(ACT_INFORMATION, ERROR_ICON_WITH_BEEP, STR_MAG_STRIPE, STR_CARD_READ_ERROR, false),
    NO_DATA_AVAILABLE(ACT_INFORMATION, INFO_ICON, STR_TOTAL_REPORT, STR_NO_DATA_AVAILABLE, false),
    PLEASE_WAIT_BR(ACT_INFORMATION, PROCESSING_ICON, STR_DATABASE_CLEAR, STR_PLEASE_WAIT_BR, false),
    CALL_CARD_CENTRE_NL_VAR(ACT_INFORMATION, PROCESSING_ICON, STR_EMPTY, STR_CALL_CARD_CENTRE_NL_VAR, true),
    SIGNATURE_REQUIRED( ACT_INFORMATION, PROCESSING_ICON, STR_EMPTY, STR_SIG_REQUIRED, false ),
    NO_RESPONSE(ACT_QUESTION, NOT_SET, NO_ICON, STR_EMPTY, STR_NO_RESPONSE),
    NO_RESPONSE_PLEASE_TRY_AGAIN(ACT_QUESTION, NOT_SET, NO_ICON, STR_EMPTY, STR_NO_RESPONSE_PLEASE_TRY_AGAIN),


    //SCREEN_DEF(SCREEN_ICON screenIcon, String_id titleId, String_id promptId,  int timeout, boolean block)
    TRANS_UPLOAD_FAILED(ERROR_ICON, STR_BATCH_UPLOAD, STR_FAILED, SHORT_TIMEOUT, true),
    NO_TRANS_TO_UPLOAD(SUCCESS_ICON, STR_BATCH_UPLOAD, STR_NO_TRANS_TO_UPLOAD, SHORT_TIMEOUT, true),
    TRANS_UPLOAD_SUCCESSFUL(SUCCESS_ICON, STR_BATCH_UPLOAD, STR_SUCCESSFUL, SHORT_TIMEOUT, true),
    DATABASE_CLEARED(SUCCESS_ICON, STR_DATABASE_CLEAR, STR_DATABASE_CLEARED, SHORT_TIMEOUT, true),
    DATABASE_EMPTY(NO_ICON, STR_DATABASE_LIST, STR_DATABASE_EMPTY, SHORT_TIMEOUT, true),
    NO_TRANS_TO_REVERSED(WARNING_ICON, STR_CLEAR_REVERSALS, STR_NO_TRANS_TO_REVERSED, SHORT_TIMEOUT, true),
    REVERSALS_CLEARED(SUCCESS_ICON, STR_CLEAR_REVERSALS, STR_REVERSALS_CLEARED, SHORT_TIMEOUT, true),
    NO_TRANSACTION_TO_RECONCILE(WARNING_ICON, STR_RECONCILIATION, STR_NO_TRANSACTION_TO_RECONCILE, SHORT_TIMEOUT, true),
    MAC_FAILURE(ERROR_ICON, STR_COMMS_ERROR, STR_MAC_FAILURE, SHORT_TIMEOUT, true),
    SERVICE_STATUS_PENDING_EVENTS(INFO_ICON, STR_SERVICE_STATUS, STR_PENDING_EVENTS, SHORT_TIMEOUT, true),
    SERVICE_STATUS_NO_PENDING_EVENTS(INFO_ICON, STR_SERVICE_STATUS, STR_NO_PENDING_EVENTS, SHORT_TIMEOUT, true),
    CARD_REMOVED_EARLY(ERROR_ICON, STR_TRANSACTION_ERROR, STR_CARD_REMOVED_EARLY, SHORT_TIMEOUT, true),
    ICC_DIAGS_ENABLED(SUCCESS_ICON, STR_ICC_DIAGS, STR_ENABLED, SHORT_TIMEOUT, true),
    ICC_DIAGS_DISABLED(SUCCESS_ICON, STR_ICC_DIAGS, STR_DISABLED, SHORT_TIMEOUT, true),
    PROCESSING_PLEASE_WAIT(INFO_ICON, STR_PROCESSING, STR_PLEASE_WAIT, LONG_TIMEOUT, false),
    PROCESSING_PLEASE_WAIT_SHORT(INFO_ICON, STR_PROCESSING, STR_PLEASE_WAIT, IUIDisplay.THREE_SEC_TIMEOUT, false),
    KEYS_RESET_SUCCESS(SUCCESS_ICON, STR_KEYS_RESET, STR_SUCCESS, ONE_SEC_TIMEOUT, false),
    TRANS_READING_CARD(PROCESSING_ICON, STR_EMPTY, STR_NL_READING_CARD, 0, false),
    TRANS_CANCELLED(ERROR_ICON, STR_EMPTY, STR_NL_CANCELLED, ONE_SEC_TIMEOUT, true),
    CANDIDATE_LIST_EMPTY(ERROR_ICON, STR_EMPTY, STR_CANDIDATE_LIST_EMPTY, FOUR_SEC_TIMEOUT, true),
    PIN_BLOCKED(ERROR_ICON, STR_EMPTY, STR_PIN_BLOCKED, FOUR_SEC_TIMEOUT, true),
    CARD_BLOCKED(ERROR_ICON, STR_EMPTY, STR_CARD_BLOCKED, FOUR_SEC_TIMEOUT, true),
    APP_BLOCKED(ERROR_ICON, STR_EMPTY, STR_APP_BLOCKED, FOUR_SEC_TIMEOUT, true),
    CAPK_NOT_FOUND(ERROR_ICON, STR_EMPTY, STR_CAPK_NOT_FOUND, FOUR_SEC_TIMEOUT, true),
    APPLICATION_EXPIRED(WARNING_ICON, STR_EMPTY, STR_APPLICATION_NL_EXPIRED, FOUR_SEC_TIMEOUT, true),
    APPLICATION_NOT_YET_EFFECTIVE(WARNING_ICON, STR_EMPTY, STR_APPLICATION_NOT_NL_YET_EFFECTIVE, FOUR_SEC_TIMEOUT, true),
    TRANSACTION_CANCELLED(ERROR_ICON, STR_EMPTY, STR_TRANSACTION_CANCELLED, 0, true),
    LAST_PIN_TRY(ERROR_ICON, STR_EMPTY, STR_LAST_PIN_TRY, FOUR_SEC_TIMEOUT, true),
    INVALID_PIN_ENTERED(ERROR_ICON, STR_EMPTY, STR_INVALID_PIN_NL_ENTERED, FOUR_SEC_TIMEOUT, true),
    CHIP_READ_ERROR_CANDIDATE_LIST_EMPTY(ERROR_ICON, STR_EMPTY, STR_CARD_TYPE_NOT_ALLOWED, FOUR_SEC_TIMEOUT, true),
    CARD_COMMAND_FAILED(ERROR_ICON, STR_EMPTY, STR_CARD_COMMAND_NL_FAILED, FOUR_SEC_TIMEOUT, true),
    REMOVE_CARD(PROCESSING_ICON_STILL, STR_EMPTY, STR_NL_NL_REMOVE_CARD, 0, false),
    REMOVE_CARD_WITH_TIMEOUT(PROCESSING_ICON_STILL, STR_EMPTY, STR_NL_NL_REMOVE_CARD, THREE_SEC_TIMEOUT, true),
    ERROR_PRESENT_ONE_CARD(ERROR_ICON_WITH_BEEP, STR_CONTLESS_WARNING, STR_ERROR_PRESENT_ONE_CARD, 0, false),
    READ_ERROR_REMOVE_CARD(ERROR_ICON_WITH_BEEP, STR_CHIP_WARNING, STR_READ_ERROR_REMOVE_CARD, 0, false),
    OUT_OF_SEQUENCE(ERROR_ICON, STR_EMPTY, STR_OUT_OF_SEQUENCE, SHORT_TIMEOUT, true),
    TRY_CONTACT_MSR_TRANS(ERROR_ICON, STR_EMPTY, STR_TRY_CONTACT_MSR_TRANS, SHORT_TIMEOUT, true),
    ZERO_TRANS_AMOUNT(ERROR_ICON, STR_EMPTY, STR_ZERO_TRANS_AMOUNT, SHORT_TIMEOUT, true),
    CARD_REPORT_ERROR(ERROR_ICON, STR_EMPTY, STR_CARD_REPORT_ERROR, SHORT_TIMEOUT, true),
    OVER_MAX_LIMIT(ERROR_ICON, STR_EMPTY, STR_OVER_MAX_LIMIT, SHORT_TIMEOUT, true),
    REQ_ONLINE_AUTH(ERROR_ICON, STR_EMPTY, STR_REQ_ONLINE_AUTH, SHORT_TIMEOUT, true),
    CARD_EXPIRED(ERROR_ICON, STR_EMPTY, STR_CARD_EXPIRED, SHORT_TIMEOUT, true),
    CARD_NO_RESPOND(ERROR_ICON, STR_EMPTY, STR_CARD_NO_RESPOND, SHORT_TIMEOUT, true),
    UNKNOWN_ELEMENT(ERROR_ICON, STR_EMPTY, STR_UNKNOWN_ELEMENT, SHORT_TIMEOUT, true),
    CARD_TYPE_NOT_READ(ERROR_ICON, STR_EMPTY, STR_CARD_TYPE_NOT_READ, SHORT_TIMEOUT, true),
    CARD_TERMINATED(ERROR_ICON, STR_EMPTY, STR_CARD_TERMINATED, SHORT_TIMEOUT, true),
    CARD_DECLINED(ERROR_ICON, STR_EMPTY, STR_CARD_DECLINED, SHORT_TIMEOUT, true),
    CARD_NOT_ACCEPTED(ERROR_ICON, STR_EMPTY, STR_CARD_NOT_ACCEPTED, SHORT_TIMEOUT, true),
    ONLINE_REQUIRED(ERROR_ICON, STR_EMPTY, STR_ONLINE_REQUIRED, SHORT_TIMEOUT, true),
    SDA_DDN_NO_SUPPORT(ERROR_ICON, STR_EMPTY, STR_SDA_DDN_NO_SUPPORT, SHORT_TIMEOUT, true),
    MISSING_CAPK(ERROR_ICON, STR_EMPTY, STR_MISSING_CAPK, SHORT_TIMEOUT, true),
    ISSUER_ERROR(ERROR_ICON, STR_EMPTY, STR_ISSUER_ERROR, SHORT_TIMEOUT, true),
    CARD_AUTH_FAIL(ERROR_ICON, STR_EMPTY, STR_CARD_AUTH_FAIL, SHORT_TIMEOUT, true),
    CARD_KEY_ERROR(ERROR_ICON, STR_EMPTY, STR_CARD_KEY_ERROR, SHORT_TIMEOUT, true),
    CARD_SIG_ERROR(ERROR_ICON, STR_EMPTY, STR_CARD_SIG_ERROR, SHORT_TIMEOUT, true),
    PROC_REST_FAIL(ERROR_ICON, STR_EMPTY, STR_PROC_REST_FAIL, SHORT_TIMEOUT, true),
    TRM_FAILED(ERROR_ICON, STR_EMPTY, STR_TRM_FAILED, SHORT_TIMEOUT, true),
    CVM_FAIL(ERROR_ICON, STR_EMPTY, STR_CVM_FAIL, SHORT_TIMEOUT, true),
    TAA_FAIL(ERROR_ICON, STR_EMPTY, STR_TAA_FAIL, SHORT_TIMEOUT, true),
    SD_MEM_ERROR(ERROR_ICON, STR_EMPTY, STR_SD_MEM_ERROR, SHORT_TIMEOUT, true),
    TRANS_TIMEOUT(ERROR_ICON, STR_EMPTY, STR_TRANS_TIMEOUT, SHORT_TIMEOUT, true),
    CARD_READ_ERROR(ERROR_ICON, STR_EMPTY, STR_CARD_READ_ERROR, SHORT_TIMEOUT, true),
    USER_DEL_OPERATION_NOT_ALLOWED(ERROR_ICON, STR_USER_DELETE, STR_OPERATION_NOT_ALLOWED, SHORT_TIMEOUT, true),
    USERS_NOT_FOUND(ERROR_ICON, STR_USER_REPORT, STR_USERS_NOT_FOUND, SHORT_TIMEOUT, true),
    ID_ALREADY_USED(ERROR_ICON, STR_EMPTY, STR_ID_ALREADY_USED, SHORT_TIMEOUT, true),
    USER_ADDED(SUCCESS_ICON, STR_EMPTY, STR_USER_ADDED, SHORT_TIMEOUT, true),
    ADD_USER_CANCELLED(ERROR_ICON, STR_EMPTY, STR_ADD_USER_CANCELLED, SHORT_TIMEOUT, true),
    USER_NOT_FOUND(ERROR_ICON, STR_EMPTY, STR_USER_NOT_FOUND, SHORT_TIMEOUT, true),
    USER_DELETED(SUCCESS_ICON, STR_EMPTY, STR_USER_DELETED, SHORT_TIMEOUT, true),
    FAILED_TO_LOGIN(ERROR_ICON, STR_EMPTY, STR_FAILED_TO_LOGIN, SHORT_TIMEOUT, true),
    PASSWORD_INCORRECT(ERROR_ICON, STR_EMPTY, STR_PASSWORD_INCORRECT, SHORT_TIMEOUT, true),
    INSUFFICIENT_PRIVILEGES(ERROR_ICON, STR_EMPTY, STR_INSUFFICIENT_PRIVILEGES, SHORT_TIMEOUT, true),
    PASSWORD_CHANGE_NOT_ALLOW(ERROR_ICON, STR_EMPTY, STR_PASSWORD_CHANGE_NOT_ALLOW, SHORT_TIMEOUT, true),
    PASSWORD_DOESNT_MATCH(ERROR_ICON, STR_EMPTY, STR_PASSWORD_DOESNT_MATCH, SHORT_TIMEOUT, true),
    PASSWORD_UPDATED(SUCCESS_ICON, STR_EMPTY, STR_PASSWORD_UPDATED, SHORT_TIMEOUT, true),
    RESET_FAILED(ERROR_ICON, STR_EMPTY, STR_RESET_FAILED, SHORT_TIMEOUT, true),
    PASSWORD_EXPIRED(ERROR_ICON, STR_EMPTY, STR_PASSWORD_EXPIRED, SHORT_TIMEOUT, true),
    PASSWORD_RESET(SUCCESS_ICON, STR_EMPTY, STR_PASSWORD_RESET, SHORT_TIMEOUT, true),
    USER_PASSWORD(ACT_QUESTION, NOT_SET, NO_ICON, STR_PRINT, STR_USER_PASSWORD),
    PROCESSING_CTLS(PROCESSING_ICON, STR_EMPTY, STR_EMPTY, MAX_TIMEOUT, false),
    PRINTER_ERROR_VAR_CHECK_PRINTER(ERROR_ICON, STR_ERROR, STR_PRINTER_ERROR_VAR_BR, SHORT_TIMEOUT, true),
    VAR_PENDING(PROCESSING_ICON, STR_BATCH_UPLOAD, STR_VAR_PENDING, IMMEDIATE_TIMEOUT, false),
    CARD_OK_REMOVE(PROCESSING_ICON, STR_EMPTY, STR_CARD_OK_REMOVE, 0, false),
    PLEASE_NL_REMOVE_CARD(PROCESSING_ICON, STR_EMPTY, STR_PLEASE_NL_REMOVE_CARD, 0, false),
    VAR_NL_PROCESSING(PROCESSING_ICON, STR_EMPTY, STR_VAR_NL_PROCESSING, MAX_TIMEOUT, false),
    VAR_NL_PROCESSING_ELLIPSIS(PROCESSING_ICON, STR_EMPTY, STR_VAR_NL_PROCESSING_ELLIPSIS, MAX_TIMEOUT, false),
    CARD_READ_OK(PROCESSING_ICON, STR_EMPTY, STR_CARD_READ_OK, MAX_TIMEOUT, false),
    PLEASE_TRY_AGAIN(PROCESSING_ICON, STR_EMPTY, STR_PLEASE_TRY_AGAIN, MAX_TIMEOUT, false),
    TRANS_APPROVED(PROCESSING_ICON, STR_EMPTY, STR_TRANS_APPROVED, MAX_TIMEOUT, false),
    TRANS_APPROVED_SIGN(PROCESSING_ICON, STR_EMPTY, STR_TRANS_APPROVED_SIGN, MAX_TIMEOUT, false),
    TRANS_DECLINED(PROCESSING_ICON, STR_EMPTY, STR_TRANS_DECLINED, MAX_TIMEOUT, false),
    TRY_ANOTHER_CARD(PROCESSING_ICON, STR_EMPTY, STR_TRY_ANOTHER_CARD, MAX_TIMEOUT, false),
    PLEASE_INSERT_CARD(PROCESSING_ICON, STR_EMPTY, STR_PLEASE_INSERT_CARD, MAX_TIMEOUT, false),
    SEE_CONSUMER_DEVICE(PROCESSING_ICON, STR_EMPTY, STR_SEE_CONSUMER_DEVICE, MAX_TIMEOUT, false),
    AUTHORISING_PLEASE_WAIT(PROCESSING_ICON, STR_EMPTY, STR_AUTHORISING_PLEASE_WAIT, MAX_TIMEOUT, false),
    EMPTY(PROCESSING_ICON, STR_EMPTY, STR_EMPTY, MAX_TIMEOUT, false),
    LOGON_FAILED(ERROR_ICON, STR_EMPTY, STR_LOGON_FAILED, SHORT_TIMEOUT, true),
    ONLY_CREDIT_ACCOUNT_ALLOWED(ERROR_ICON, STR_EMPTY, STR_ONLY_CREDIT_ACCOUNT_ALLOWED, FOUR_SEC_TIMEOUT, true),
    KEY_INJECTION_REQUIRED(ERROR_ICON, STR_TRANSACTION_CANCELLED, STR_KEY_INJECTION_REQUIRED, SHORT_TIMEOUT, true),


    // SCREEN_DEF(SCREEN_ICON screenIcon, String_id titleId, String_id promptId, int timeout, boolean dismissible, SCREEN_ICON additionalScreenIcon )
    RECEIPT_NOT_FOUND(ERROR_ICON, STR_REPRINT, STR_RECEIPT_NOT_FOUND, SHORT_TIMEOUT, true, PRINTING_ICON),
    BATTERY_LOW_PLEASE_CHARGE(ERROR_ICON, STR_ERROR, STR_BATTERY_LOW_PLEASE_CHARGE, THREE_SEC_TIMEOUT, true, PRINTING_ICON),
    PAPER_OUT_PLEASE_INSERT(ACT_QUESTION, NOT_SET, NO_ICON, STR_PRINTING, STR_PAPER_OUT_PLEASE_INSERT),
    OUT_OF_PAPER(WARNING_ICON, STR_PRINTER, STR_OUT_OF_PAPER, EXTRA_LONG_TIMEOUT, true, PRINTING_ICON),
    PRINTING_PLEASE_WAIT_PROCESSING(PROCESSING_ICON, STR_PRINTING, STR_NL_PLEASE_WAIT, LONG_TIMEOUT, false, PRINTING_ICON),
    PRINTING_PLEASE_WAIT_SUCCESS(SUCCESS_ICON, STR_PRINTING, STR_NL_PLEASE_WAIT, LONG_TIMEOUT, false, PRINTING_ICON),
    PRINTING_PLEASE_WAIT_ERROR(ERROR_ICON, STR_PRINTING, STR_NL_PLEASE_WAIT, LONG_TIMEOUT, false, PRINTING_ICON),
    PRINTING_COMPLETED_SUCCESS(SUCCESS_ICON, STR_PRINTING, STR_NL_COMPLETED, THREE_SEC_TIMEOUT, true, PRINTING_ICON),
    PRINTING_COMPLETED_ERROR(ERROR_ICON, STR_PRINTING, STR_NL_COMPLETED, THREE_SEC_TIMEOUT, true, PRINTING_ICON),
    PRINTER_ERROR_VAR_BR(ERROR_ICON, STR_ERROR, STR_PRINTER_ERROR_VAR_BR, THREE_SEC_TIMEOUT, true, PRINTING_ICON),

    // SCREEN_DEF(String_id titleId, String_id promptId,  String_id btnPromptId, int timeout, boolean block)
    TIMESYNC(STR_EMPTY_STR, STR_TIMESYNC, STR_CONTINUE, LONG_TIMEOUT, true),
    SENDING_VAR_OF_VAR(PROCESSING_ICON, STR_BATCH_UPLOAD, STR_SENDING_VAR_OF_VAR, STR_CANCEL_RETURN_MENU, IMMEDIATE_TIMEOUT, true),
    UPLOADED_VAR_OF_VAR_NL_UPLOAD_WILL_CONTINUE(STR_BATCH_UPLOAD, STR_UPLOADED_VAR_OF_VAR_NL_UPLOAD_WILL_CONTINUE, STR_OK, INFO_TIMEOUT, true),

    // UIScreenDef(ACTIVITY_ID id, SCREEN_ID screenId, SCREEN_ICON screenIcon, String_id titleId, String_id promptId, String_id hintId )
    ENTER_AMOUNT(ACT_INPUT_AMOUNT, NOT_SET, NO_ICON, STR_EMPTY, STR_ENTER_AMOUNT, STR_EMPTY, 1, 100),
    ENTER_AMOUNT_IDLE(ACT_INPUT_AMOUNT_IDLE, NOT_SET, NO_ICON, STR_EMPTY, STR_ENTER_AMOUNT, STR_EMPTY, 1, 100),
    ENTER_TOTAL_PREAUTH_AMT(ACT_INPUT_AMOUNT, NOT_SET, NO_ICON, STR_EMPTY, STR_ENTER_TOTAL_PREAUTH_AMT, STR_EMPTY, 1, 100),
    ENTER_NAME(ACT_INPUT, GET_INPUT_ALPHA_NUMERIC, NO_ICON, STR_EMPTY, STR_ENTER_NAME, STR_DISPLAY_NAME, DEFAULT_VALUES.MIN_USERNAME_LEN, DEFAULT_VALUES.MAX_USERNAME_LEN),
    REENTER_NEW_PASSWORD(ACT_INPUT, GET_INPUT_NUMBER_PASSWORD, NO_ICON, STR_EMPTY, STR_REENTER_NEW_PASSWORD, STR_NEW_PASSWORD, DEFAULT_VALUES.MIN_PASSWORD_LEN, DEFAULT_VALUES.MAX_PASSWORD_LEN),
    ENTER_EXISTING_PASSWORD(ACT_INPUT, GET_INPUT_NUMBER_PASSWORD, NO_ICON, STR_EMPTY, STR_ENTER_EXISTING_PASSWORD, STR_PASSWORD, DEFAULT_VALUES.MIN_PASSWORD_LEN, DEFAULT_VALUES.MAX_PASSWORD_LEN),
    ENTER_NEW_PASSWORD(ACT_INPUT, GET_INPUT_NUMBER_PASSWORD, NO_ICON, STR_EMPTY, STR_ENTER_NEW_PASSWORD, STR_NEW_PASSWORD, DEFAULT_VALUES.MIN_PASSWORD_LEN, DEFAULT_VALUES.MAX_PASSWORD_LEN),
    ENTER_PASSWORD(ACT_INPUT, GET_INPUT_NUMBER_PASSWORD, NO_ICON, STR_EMPTY, STR_ENTER_PASSWORD, STR_PASSWORD, DEFAULT_VALUES.MIN_PASSWORD_LEN, DEFAULT_VALUES.MAX_PASSWORD_LEN),
    ENTER_USER_ID(ACT_INPUT, GET_INPUT_NUMBER, NO_ICON, STR_EMPTY, STR_ENTER_USER_ID, STR_USER_ID, DEFAULT_VALUES.MIN_USERNAME_LEN, DEFAULT_VALUES.MAX_USERNAME_LEN),
    ENTER_HOUSE_NO(ACT_INPUT, GET_INPUT_NUMBER, NO_ICON, STR_EMPTY, STR_ENTER_HOUSE_NUMBER, STR_INPUT_HINT_4LEN, 1, 5),
    ENTER_AUTH_CODE(ACT_INPUT, GET_INPUT_NUMERIC_ALPHA_NO_SYM, NO_ICON, STR_EMPTY, STR_ENTER_AUTH_CODE, STR_EMPTY, 1, 6),
    ENTER_REFERENCE(ACT_INPUT, GET_INPUT_NUMERIC_ALPHA_NO_SYM, NO_ICON, STR_EMPTY, STR_ENTER_REFERENCE, STR_ENTER_HERE, 0, DEFAULT_VALUES.REFERENCE_LEN),
    ENTER_EMAIL(ACT_INPUT, GET_INPUT_EMAIL, NO_ICON, STR_EMPTY, STR_ENTER_EMAIL, STR_ENTER_HERE, 0, DEFAULT_VALUES.EMAIL_LEN),
    REFERENCE_VAR(ACT_INPUT, GET_INPUT_NUMERIC_ALPHA_NO_SYM, NO_ICON, STR_REFERENCE, STR_VAR, STR_ENTER_HERE, 0, DEFAULT_VALUES.REFERENCE_LEN),
    ENTER_NUMBER_TRANSACTIONS(ACT_INPUT, GET_INPUT_NUMBER, NO_ICON, STR_EMPTY, STR_NUMBER_TRANSACTIONS, STR_EMPTY, 1, 3),
    ENTER_NUMBER_KEY_ITERATIONS(ACT_INPUT, GET_INPUT_NUMBER, NO_ICON, STR_EMPTY, STR_NUMBER_KEY_ITERATIONS, STR_EMPTY, 1, 6),
    ENTER_POST_CODE(ACT_INPUT, GET_INPUT_NUMBER, NO_ICON, STR_EMPTY, STR_ENTER_POST_CODE, STR_INPUT_HINT_3LEN, 1, 5),
    ENTER_RECEIPT_NUM(ACT_INPUT, GET_INPUT_NUMBER, NO_ICON, STR_EMPTY, STR_ENTER_RECEIPT_NUM, STR_NUMBER, 1, 6),
    ENTER_PREAUTH_RRN_CODE(ACT_INPUT, GET_INPUT_ALPHA_NUMERIC, NO_ICON, STR_EMPTY, STR_ENTER_PREAUTH_RRN_CODE, STR_ENTER_HERE, 1, 12),
    ENTER_PREAUTH_AUTHCODE(ACT_INPUT, GET_INPUT_NUMBER, NO_ICON, STR_EMPTY, STR_ENTER_PREAUTH_AUTHCODE, STR_ENTER_HERE, 6, 6),
    ENTER_EFB_AUTH_NUMBER(ACT_INPUT, GET_INPUT_NUMBER, NO_ICON, STR_EMPTY, STR_ENTER_EFB_AUTH_NUMBER, STR_ENTER_HERE, 6, 6),
    ADMIN_PASSWORD(ACT_INPUT, GET_INPUT_PASSWORD, NO_ICON, STR_SECURITY_CHECK, STR_ADMIN_PASSWORD, STR_EMPTY, 1, 6),
    ENTER_USER_CREDENTIALS(ACT_USER_LOGIN, NOT_SET, NO_ICON, STR_WELCOME, STR_ENTER_USER_CREDENTIALS, STR_EMPTY, DEFAULT_VALUES.MIN_USERNAME_LEN, DEFAULT_VALUES.MAX_USERNAME_LEN),
    DISPLAY_DEFERRED_AUTHS(ACT_DEFERRED_AUTHS, NOT_SET, NO_ICON, STR_EMPTY, STR_DEFERRED_AUTHS),
    MERCHANT_EMAIL_QUEUED(SUCCESS_ICON, STR_PRINTING, STR_MERCHANT_EMAIL_QUEUED, SHORT_TIMEOUT, false),
    CUSTOMER_EMAIL_QUEUED(SUCCESS_ICON, STR_PRINTING, STR_CUSTOMER_EMAIL_QUEUED, SHORT_TIMEOUT, false),
    CARD_READ_MAGSTRIPE_COMMAND_SUCCESSFUL(SUCCESS_ICON, STR_MAG_STRIPE, STR_CARD_READ_OK, SHORT_TIMEOUT, false),
    CARD_READ_CONTACTLESS_COMMAND_SUCCESSFUL(SUCCESS_ICON, STR_CONTACTLESS, STR_CARD_READ_OK, SHORT_TIMEOUT, false),

    CARD_READ_EMV_COMMAND_SUCCESSFUL(SUCCESS_ICON, STR_CHIP_READ_OK, STR_CARD_READ_OK, SHORT_TIMEOUT, false),
    VIEW_RECEIPT(ACT_SCREEN_PRINT, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY),
    VIEW_ANIMATED_RECEIPT(ACT_ANIMATED_PRINT, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY),
    GET_SIGNATURE(ACT_SIG, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY),
    SELECT_RECEIPT(ACT_QUESTION, NOT_SET, NO_ICON, STR_PRINTING, STR_SELECT_RECEIPT),
    PLB_RESTRICTED_ITEM(ACT_INFORMATION, NOT_SET, ERROR_ICON, STR_EMPTY, STR_PLB_RESTRICTED_ITEM),
    PREAUTH_NOT_FOUND(ERROR_ICON, STR_EMPTY, STR_PREAUTH_NOT_FOUND, SHORT_TIMEOUT, true),
    PREAUTH_NOT_FOUND_TRY_AGAIN(ERROR_ICON, STR_EMPTY, STR_PREAUTH_NOT_FOUND_TRY_AGAIN, SHORT_TIMEOUT, true),
    RFN_NOT_ENTERED(ERROR_ICON, STR_EMPTY, STR_RFN_NOT_ENTERED, SHORT_TIMEOUT, true),
    EXCEEDS_PREAUTH_AMT(ERROR_ICON, STR_EMPTY, STR_AMT_EXCEEDS_PREAUTH_AMT, SHORT_TIMEOUT, true),
    PREAUTH_WAS_CANCELLED(ERROR_ICON, STR_EMPTY, STR_PREAUTH_WAS_CANCELLED, SHORT_TIMEOUT, true),
    PREAUTH_EXISTS(ERROR_ICON, STR_EMPTY, STR_PREAUTH_EXISTS, SHORT_TIMEOUT, true),
    IS_CARDHOLDER_PRESENT(ACT_QUESTION, NOT_SET, NO_ICON, STR_EMPTY, STR_IS_CARDHOLDER_PRESENT),
    DISPLAY_SAF_VIEW_AND_CLEAR(ACT_SAF_VIEW_AND_CLEAR, NOT_SET, NO_ICON, STR_EMPTY, STR_SAF_VIEW_AND_CLEAR),
    DISPLAY_TRANSACTION_HISTORY(ACT_TRANSACTION_HISTORY, NOT_SET, NO_ICON, STR_EMPTY, STR_SAF_VIEW_AND_CLEAR,EXTRA_LONG_TIMEOUT),
    SAF_RECORD_DELETED(NO_ICON, STR_EMPTY, STR_SAF_RECORD_DELETED, SHORT_TIMEOUT, true),
    PERMISSIONS_ERROR(ACT_INFORMATION, ERROR_ICON, STR_PERMISSIONS_ERROR, STR_EMPTY, true),
    UNABLE_TO_READ_RECORD(ACT_INFORMATION, NO_ICON, STR_RECORD_UNABLE_TO_READ, STR_EMPTY, true),
    DISPLAY_PRE_AUTH_SEARCH_AND_VIEW_SELECT_DATE(ACT_PRE_AUTH_SEARCH_AND_VIEW_SELECT_DATE, NOT_SET, NO_ICON, STR_PRE_AUTH_SEARCH_AND_VIEW_SELECT_DATE, STR_EMPTY),
    DISPLAY_PRE_AUTH_SEARCH_AND_VIEW(ACT_PRE_AUTH_SEARCH_AND_VIEW, NOT_SET, NO_ICON, STR_EMPTY, STR_PRE_AUTH_SEARCH_AND_VIEW, EXTRA_LONG_TIMEOUT),
    ENTER_RRN(ACT_INPUT, GET_INPUT_NUMERIC_ALPHA_NO_SYM, NO_ICON, STR_EMPTY, STR_ENTER_RRN, STR_EMPTY, 1, 12),
    USER_IS_LOCKED_TOO_MANY_PASSCODE_ATTEMPTS(ERROR_ICON, STR_EMPTY, STR_USER_IS_LOCKED_TOO_MANY_PASSCODE_ATTEMPTS, THREE_SEC_TIMEOUT, true),
    TOTAL_OFFLINE_TRANS_AMOUNT_LIMIT_EXCEEDED(ERROR_ICON, STR_EMPTY, STR_TOTAL_OFFLINE_TRANS_AMOUNT_LIMIT_EXCEEDED, SHORT_TIMEOUT, true),
    OFFLINE_TRANS_AMOUNT_LIMIT_EXCEEDED(ERROR_ICON, STR_EMPTY, STR_OFFLINE_TRANS_AMOUNT_LIMIT_EXCEEDED, SHORT_TIMEOUT, true),
    OFFLINE_TRANS_COUNT_LIMIT_EXCEEDED(ERROR_ICON, STR_EMPTY, STR_OFFLINE_TRANS_COUNT_LIMIT_EXCEEDED, SHORT_TIMEOUT, true),
    OFFLINE_TRANS_CLOSE_TO_LIMIT(ACT_QUESTION, WARNING_ICON, STR_EMPTY, STR_OFFLINE_TRANS_CLOSE_TO_LIMIT, true),
    // Add screen definitions above this
    REFUND_LIMIT_EXCEEDED(ERROR_ICON, STR_EMPTY, STR_REFUND_LIMIT_EXCEEDED, SHORT_TIMEOUT, true),
    REFUND_COUNT_LIMIT_EXCEEDED(ERROR_ICON, STR_EMPTY, STR_REFUND_COUNT_LIMIT_EXCEEDED, SHORT_TIMEOUT, true),
    DEFAULT_SCREEN(ACT_INFORMATION, NOT_SET, NO_ICON, STR_EMPTY, STR_EMPTY);

    UIScreenDef(ACTIVITY_ID id, SCREEN_ID screenId, SCREEN_ICON screenIcon, String_id titleId, String_id promptId) {
        this(id, screenId, screenIcon, titleId, promptId, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, DEFAULT_VALUES.TIMEOUT, DEFAULT_VALUES.DISMISSIBLE, DEFAULT_VALUES.BLOCK, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN);
    }

    UIScreenDef(ACTIVITY_ID id, SCREEN_ICON screenIcon, String_id titleId, String_id promptId, boolean dismissible) {
        this(id, DEFAULT_VALUES.SCREEN_ID, screenIcon, titleId, promptId, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, DEFAULT_VALUES.TIMEOUT, dismissible, DEFAULT_VALUES.BLOCK, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN);
    }

    UIScreenDef(SCREEN_ID screenId, SCREEN_ICON screenIcon, String_id titleId, String_id promptId, int timeout, boolean block) {
        this(DEFAULT_VALUES.ID, screenId, screenIcon, titleId, promptId, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, timeout, DEFAULT_VALUES.DISMISSIBLE, block, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN);
    }

    UIScreenDef(SCREEN_ICON screenIcon, String_id titleId, String_id promptId, int timeout, boolean block) {
        this(DEFAULT_VALUES.ID, DEFAULT_VALUES.SCREEN_ID, screenIcon, titleId, promptId, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, timeout, DEFAULT_VALUES.DISMISSIBLE, block, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN);
    }

    UIScreenDef(SCREEN_ICON screenIcon, String_id titleId, String_id promptId, String_id btnPromptId, int timeout, boolean block) {
        this(DEFAULT_VALUES.ID, DEFAULT_VALUES.SCREEN_ID, screenIcon, titleId, promptId, btnPromptId, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, timeout, DEFAULT_VALUES.DISMISSIBLE, block, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN);
    }

    UIScreenDef(String_id titleId, String_id promptId, String_id btnPromptId, int timeout, boolean block) {
        this(DEFAULT_VALUES.ID, DEFAULT_VALUES.SCREEN_ID, DEFAULT_VALUES.ICON, titleId, promptId, btnPromptId, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, timeout, DEFAULT_VALUES.DISMISSIBLE, block, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN);
    }

    UIScreenDef(SCREEN_ICON screenIcon, String_id titleId, String_id promptId, int timeout, boolean dismissible, SCREEN_ICON additionalScreenIcon) {
        this(DEFAULT_VALUES.ID, DEFAULT_VALUES.SCREEN_ID, screenIcon, titleId, promptId, DEFAULT_VALUES.STRING, additionalScreenIcon, DEFAULT_VALUES.STRING, timeout, dismissible, DEFAULT_VALUES.BLOCK, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN);
    }

    UIScreenDef(ACTIVITY_ID id, SCREEN_ID screenId, SCREEN_ICON screenIcon, String_id titleId, String_id promptId, String_id hintId, int minLen, int maxLen) {
        this(id, screenId, screenIcon, titleId, promptId, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, hintId, DEFAULT_VALUES.TIMEOUT, DEFAULT_VALUES.DISMISSIBLE, DEFAULT_VALUES.BLOCK, minLen, maxLen);
    }

    UIScreenDef(ACTIVITY_ID id, SCREEN_ID screenId, SCREEN_ICON screenIcon,
                String_id titleId, String_id promptId, String_id buttonPromptId,
                SCREEN_ICON additionalScreenIcon, String_id hintId,
                int timeout, boolean dismissible, boolean block, int minLen, int maxLen) {
        this.id = id;
        this.screenId = screenId;
        this.screenIcon = screenIcon;
        this.titleId = titleId;
        this.promptId = promptId;
        this.buttonPromptId = buttonPromptId;
        this.additionalScreenIcon = additionalScreenIcon;
        this.dismissible = dismissible;
        this.block = block;
        this.hintId = hintId;
        this.timeout = timeout;
        this.minLen = minLen;
        this.maxLen = maxLen;
    }

    UIScreenDef(ACTIVITY_ID id, SCREEN_ID screenId, SCREEN_ICON screenIcon, String_id titleId, String_id promptId, int timeout) {
        this(id, screenId, screenIcon, titleId, promptId, DEFAULT_VALUES.STRING, DEFAULT_VALUES.ICON, DEFAULT_VALUES.STRING, timeout, DEFAULT_VALUES.DISMISSIBLE, DEFAULT_VALUES.BLOCK, DEFAULT_VALUES.ENTRY_LEN, DEFAULT_VALUES.ENTRY_LEN);
    }

    private static final class DEFAULT_VALUES {
        private static final boolean DISMISSIBLE = true;
        private static final boolean BLOCK = false;
        private static final int TIMEOUT = NO_TIMEOUT;
        private static final String_id STRING = STR_EMPTY;
        private static final SCREEN_ICON ICON = NO_ICON;
        private static final ACTIVITY_ID ID = ACT_INFORMATION;
        private static final SCREEN_ID SCREEN_ID = NOT_SET;
        private static final int ENTRY_LEN = 0;
        private static final int MIN_USERNAME_LEN = 4;
        private static final int MIN_PASSWORD_LEN = 6;
        private static final int MAX_USERNAME_LEN = 8;
        private static final int MAX_PASSWORD_LEN = 12;
        private static final int REFERENCE_LEN = 20;
        private static final int EMAIL_LEN = 40;

    }

    public String_id promptId;
    public SCREEN_ICON screenIcon;
    public ACTIVITY_ID id;
    public SCREEN_ID screenId;
    public String_id titleId;
    public String_id buttonPromptId;
    public SCREEN_ICON additionalScreenIcon;
    public String_id hintId;
    public boolean dismissible;
    public int timeout;
    public boolean block;
    public int minLen;
    public int maxLen;
}
